export const accounts = [
  { id: "ar1", name: "Accounts Receivable" },
];

export const MAX_CUSTOMER_DOCUMENTS = 3;

export const contactStatusOptions = [
  { value: "active", label: "Active" },
  { value: "inactive", label: "Inactive" },
];

export const vatTreatmentOptions = [
  { value: "", label: "Select VAT treatment" },
  { value: "uk", label: "UK" },
  { value: "eu_vat_registered", label: "EU VAT registered" },
  { value: "overseas", label: "Overseas" },
];

export const taxTreatmentOptions = [
  { value: "", label: "Select tax treatment" },
  { value: "home_country_mexico", label: "Home country Mexico" },
  { value: "border_region_mexico", label: "Border region Mexico" },
  { value: "non_mexico", label: "Non Mexico" },
];

export const taxRegimeOptions = [
  { value: "", label: "Select tax regime" },
  { value: "general_legal_person", label: "General legal person" },
  { value: "legal_entities_non_profit", label: "Legal entities non-profit" },
  { value: "resident_abroad", label: "Resident abroad" },
  { value: "production_cooperative_societies", label: "Production cooperative societies" },
  { value: "agricultural_livestock", label: "Agricultural livestock" },
  { value: "optional_group_of_companies", label: "Optional group of companies" },
  { value: "coordinated", label: "Coordinated" },
  { value: "simplified_trust", label: "Simplified trust" },
  { value: "wages_salaries_income", label: "Wages and salaries income" },
  { value: "lease", label: "Lease" },
  { value: "property_disposal_acquisition", label: "Property disposal acquisition" },
  { value: "other_income", label: "Other income" },
  { value: "divident_income", label: "Dividend income" },
  { value: "individual_business_professional", label: "Individual business professional" },
  { value: "interest_income", label: "Interest income" },
  { value: "income_obtaining_price", label: "Income obtaining price" },
  { value: "no_tax_obligation", label: "No tax obligation" },
  { value: "tax_incorporation", label: "Tax incorporation" },
  { value: "income_through_technology_platform", label: "Income through technology platform" },
];

export const gstTreatmentOptions = [
  { value: "", label: "Select GST treatment" },
  { value: "business_gst", label: "Business GST" },
  { value: "business_none", label: "Business unregistered" },
  { value: "overseas", label: "Overseas" },
  { value: "consumer", label: "Consumer" },
];

export const customerLanguageOptions = [
  { value: "arabic-egyptian", label: "العربية (المصرية)" },
  { value: "arabic", label: "العربية" },
  { value: "bulgarian", label: "български" },
  { value: "german", label: "Deutsch" },
  { value: "english", label: "English" },
  { value: "spanish", label: "español" },
  { value: "filipino", label: "Filipino" },
  { value: "french", label: "français" },
  { value: "french-canada", label: "français (Canada)" },
  { value: "croatian", label: "hrvatski" },
  { value: "indonesian", label: "Bahasa Indonesia" },
  { value: "italian", label: "italiano" },
  { value: "japanese", label: "日本語" },
  { value: "kannada", label: "ಕನ್ನಡ" },
  { value: "korean", label: "한국어" },
  { value: "marathi", label: "मराठी" },
  { value: "malay", label: "Bahasa Melayu" },
  { value: "dutch", label: "Nederlands" },
  { value: "portuguese", label: "português" },
  { value: "swedish", label: "svenska" },
  { value: "thai", label: "ไทย" },
  { value: "vietnamese", label: "Tiếng Việt" },
  { value: "chinese-simplified", label: "中文 - 简体" },
  { value: "chinese-traditional", label: "中文 - 繁體" },
];

export const createDefaultContactPerson = () => ({
  id: Date.now(),
  salutation: "",
  firstName: "",
  lastName: "",
  email: "",
  workPhonePrefix: "+358",
  workPhone: "",
  mobilePrefix: "+252",
  mobile: "",
  skypeName: "",
  designation: "",
  department: "",
  isPrimary: false,
});

export const createDefaultCustomerFormData = () => ({
  customerType: "business",
  salutation: "",
  firstName: "",
  lastName: "",
  companyName: "",
  displayName: "",
  email: "",
  workPhonePrefix: "+358",
  workPhone: "",
  mobilePrefix: "+252",
  mobile: "",
  customerLanguage: "english",
  isTrackedForMoss: false,
  taxRate: "",
  companyId: "",
  locationCode: "",
  currency: "USD",
  exchangeRate: "1.00",
  accountsReceivable: "",
  openingBalance: "",
  paymentTerms: "due-on-receipt",
  priceListId: "",
  enablePortal: false,
  paymentReminderEnabled: false,
  isLinkedWithZohoCrm: false,
  status: "active",
  customerOwner: "",
  websiteUrl: "",
  department: "",
  designation: "",
  xHandle: "",
  skypeName: "",
  facebook: "",
  vatRegNo: "",
  taxRegNo: "",
  countryCode: "",
  vatTreatment: "",
  taxTreatment: "",
  taxRegime: "",
  legalName: "",
  isTdsRegistered: false,
  placeOfContact: "",
  gstNo: "",
  gstTreatment: "",
  taxAuthorityName: "",
  taxExemptionCode: "",
  avataxExemptNo: "",
  avataxUseCode: "",
  taxExemptionId: "",
  taxAuthorityId: "",
  tdsTaxId: "",
  defaultTemplates: {} as Record<string, any>,
  customerNumber: "CUS-00003",
  billingAttention: "",
  billingCountry: "",
  billingStreet1: "",
  billingStreet2: "",
  billingCity: "",
  billingState: "",
  billingZipCode: "",
  billingPhonePrefix: "+252",
  billingPhone: "",
  billingFax: "",
  shippingAttention: "",
  shippingCountry: "",
  shippingStreet1: "",
  shippingStreet2: "",
  shippingCity: "",
  shippingState: "",
  shippingZipCode: "",
  shippingPhonePrefix: "+252",
  shippingPhone: "",
  shippingFax: "",
  documents: [] as any[],
  contactPersons: [] as any[],
  customFields: {} as Record<string, any>,
  reportingTags: [] as any[],
  remarks: "",
});

export type CustomerFormData = ReturnType<typeof createDefaultCustomerFormData>;
export type CustomerContactPerson = ReturnType<typeof createDefaultContactPerson>;
