export interface CustomerColumn {
  key: string;
  label: string;
  visible: boolean;
  pinned: boolean;
  width: number;
}

export const DEFAULT_CUSTOMER_VIEWS = [
  "All Customers",
  "Active Customers",
  "CRM Customers",
  "Duplicate Customers",
  "Inactive Customers",
  "Customer Portal Enabled",
  "Customer Portal Disabled",
  "Overdue Customers",
  "Unpaid Customers",
];

export const DEFAULT_CUSTOMER_COLUMNS: CustomerColumn[] = [
  { key: "name", label: "Name", visible: true, pinned: true, width: 200 },
  { key: "companyName", label: "Company Name", visible: true, pinned: false, width: 200 },
  { key: "email", label: "Email", visible: false, pinned: false, width: 250 },
  { key: "workPhone", label: "Phone", visible: true, pinned: false, width: 150 },
  { key: "receivables_bcy", label: "Receivables (BCY)", visible: true, pinned: false, width: 180 },
  { key: "unused_credits_bcy", label: "Unused Credits (BCY)", visible: true, pinned: false, width: 150 },
  { key: "receivables", label: "Receivables", visible: false, pinned: false, width: 150 },
  { key: "unusedCredits", label: "Unused Credits", visible: false, pinned: false, width: 150 },
  { key: "source", label: "Source", visible: false, pinned: false, width: 120 },
  { key: "customerNumber", label: "Customer Number", visible: false, pinned: false, width: 150 },
  { key: "first_name", label: "First Name", visible: false, pinned: false, width: 120 },
  { key: "last_name", label: "Last Name", visible: false, pinned: false, width: 120 },
  { key: "mobile", label: "Mobile Phone", visible: false, pinned: false, width: 150 },
  { key: "payment_terms", label: "Payment Terms", visible: false, pinned: false, width: 150 },
  { key: "status", label: "Status", visible: false, pinned: false, width: 100 },
  { key: "website", label: "Website", visible: false, pinned: false, width: 180 },
];

export const CUSTOMER_SEARCH_TYPES = [
  "Customers",
  "Items",
  "Inventory Adjustments",
  "Banking",
  "Quotes",
  "Invoices",
  "Payments Received",
  "Recurring Invoices",
  "Credit Notes",
  "Vendors",
  "Expenses",
  "Recurring Expenses",
  "Purchase Orders",
  "Bills",
  "Payments Made",
  "Recurring Bills",
  "Vendor Credits",
  "Projects",
  "Timesheet",
  "Journals",
  "Chart of Accounts",
  "Documents",
  "Task",
];

export const CUSTOMER_SEARCH_COMPARATORS = [
  "is",
  "is not",
  "starts with",
  "contains",
  "doesn't contain",
  "is in",
  "is not in",
  "is empty",
  "is not empty",
];

export const CUSTOMER_DECIMAL_FORMATS = [
  "1234567.89",
  "1,234,567.89",
  "1234567,89",
  "1.234.567,89",
];

export const CUSTOMER_EXPORT_MODULES = [
  "Quotes",
  "Invoices",
  "Invoice Payments",
  "Recurring Invoices",
  "Credit Notes",
  "Credit Notes Applied to Invoices",
  "Refunds",
  "Purchase",
  "Expenses",
  "Recurring Expenses",
  "Purchase Orders",
  "Bills",
  "Bill Payments",
  "Recurring Bills",
  "Vendor Credits",
  "Applied Vendor Credits",
  "Vendor Credit Refunds",
  "Timesheet",
  "Projects",
  "Project Tasks",
  "Others",
  "Customers",
  "Vendors",
  "Tasks",
  "Items",
  "Inventory Adjustments",
  "Exchange Rates",
  "Users",
  "Chart of Accounts",
  "Manual Journals",
  "Documents",
  "Export Template",
];

export const CUSTOMER_PORTAL_LANGUAGES = [
  "English",
  "Spanish",
  "French",
  "German",
  "Arabic",
  "Chinese",
  "Japanese",
  "Somali",
  "Hindi",
  "Portuguese",
  "Russian",
  "Italian",
  "Dutch",
  "Korean",
  "Turkish",
  "Polish",
  "Swedish",
  "Norwegian",
  "Danish",
  "Finnish",
  "Greek",
  "Czech",
  "Hungarian",
  "Romanian",
  "Bulgarian",
  "Croatian",
  "Serbian",
  "Ukrainian",
  "Estonian",
  "Latvian",
  "Lithuanian",
  "Slovak",
  "Slovenian",
  "Irish",
  "Scottish Gaelic",
  "Welsh",
  "Basque",
  "Catalan",
  "Galician",
  "Icelandic",
  "Maltese",
  "Albanian",
  "Macedonian",
  "Bosnian",
  "Montenegrin",
  "Belarusian",
  "Moldovan",
  "Armenian",
  "Georgian",
  "Azerbaijani",
  "Kazakh",
  "Kyrgyz",
  "Tajik",
  "Turkmen",
  "Uzbek",
  "Mongolian",
  "Nepali",
  "Bengali",
  "Tamil",
  "Telugu",
  "Marathi",
  "Gujarati",
  "Kannada",
  "Malayalam",
  "Punjabi",
  "Sinhala",
  "Burmese",
  "Khmer",
  "Lao",
  "Thai",
  "Vietnamese",
  "Indonesian",
  "Malay",
  "Filipino",
  "Javanese",
  "Sundanese",
  "Malagasy",
  "Swahili",
  "Zulu",
  "Afrikaans",
  "Amharic",
  "Oromo",
  "Tigrinya",
  "Yoruba",
  "Igbo",
  "Hausa",
  "Wolof",
  "Berber",
  "Hebrew",
  "Pashto",
  "Urdu",
  "Persian",
  "Dari",
  "Uyghur",
  "Tibetan",
  "Mandarin",
  "Cantonese",
  "Taiwanese",
  "Hakka",
];

export const CUSTOMER_ACCOUNTS_RECEIVABLE_OPTIONS = ["Accounts Receivable"];

