import type { ReportCategory, ReportDefinition, ReportFunctionKey } from "./types";

const support = (...keys: ReportFunctionKey[]) =>
  keys.reduce((acc, key) => {
    acc[key] = true;
    return acc;
  }, {} as Partial<Record<ReportFunctionKey, boolean>>);

const safeDivide = (numerator: number, denominator: number) => (denominator === 0 ? 0 : numerator / denominator);

export const REPORT_FUNCTION_LABELS: { key: ReportFunctionKey; label: string }[] = [
  { key: "filter", label: "Filter Report" },
  { key: "compare", label: "Compare Report" },
  { key: "group", label: "Group Report" },
  { key: "performance", label: "Performance Overview" },
  { key: "customizeColumns", label: "Customize Report Columns" },
  { key: "sort", label: "Sort Columns" },
  { key: "schedule", label: "Schedule Report" },
  { key: "share", label: "Share Report" },
  { key: "export", label: "Export Report" },
  { key: "print", label: "Print Report" },
  { key: "custom", label: "Custom Report" },
];

export const REPORT_CATEGORIES: ReportCategory[] = [
  {
    id: "sales",
    name: "Sales Reports",
    description: "Track sales across customers, items, plans, addons, coupons, salespersons, and daily summary.",
  },
  {
    id: "receivables",
    name: "Receivables Reports",
    description: "Monitor outstanding amounts, aging intervals, receivable transactions, and bad debts.",
  },
  {
    id: "acquisition-insights",
    name: "Acquisition Insights",
    description: "Analyze trial pipeline, conversions, sales cycle, and opportunities lost during onboarding.",
  },
  {
    id: "signups-activations",
    name: "Signups and Activations",
    description: "Understand subscription signups, activations, and active user distribution by country.",
  },
  {
    id: "revenue",
    name: "Revenue Reports",
    description: "Measure net revenue and country-level revenue contributions.",
  },
  {
    id: "subscriptions",
    name: "Subscriptions Reports",
    description: "Track active subscriptions, net customers, upgrades, downgrades, ARPU, and LTV.",
  },
  {
    id: "churn",
    name: "Churn Reports",
    description: "Track at-risk profiles, non-renewals, post-dunning churn, and expiry cohorts.",
  },
  {
    id: "churn-insights",
    name: "Churn Insights",
    description: "Measure net cancellations, churn rate, and revenue churn trends.",
  },
  {
    id: "payments-received",
    name: "Payments Received",
    description: "Review payments, due intervals, credit notes, refunds, failures, and card expiry.",
  },
  {
    id: "purchases-expenses",
    name: "Purchases and Expenses",
    description: "Track expense totals, categories, customer/project split, and billable expenses.",
  },
  {
    id: "projects-timesheets",
    name: "Projects and Timesheets",
    description: "Inspect timesheet details, project summaries, and project revenue performance.",
  },
  {
    id: "activity",
    name: "Activity Reports",
    description: "Audit mails, user actions, portal activity, and customer reviews.",
  },
  {
    id: "mrr-arr",
    name: "MRR and ARR",
    description: "Measure recurring revenue health using MRR, ARR, and MRR Quick Ratio.",
  },
];

export const REPORTS: ReportDefinition[] = [
  {
    id: "sales-by-customer",
    categoryId: "sales",
    name: "Sales by Customer",
    summary: "Breakdown of customers with total sales for each customer.",
    howItHelps: "Identify top customers and build retention or loyalty actions around high-value accounts.",
    basis: "Accrual",
    source: "Invoices, Credit Notes, Sales Receipts (configurable view)",
    functionSupport: support("filter", "compare", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },
  {
    id: "sales-by-item",
    categoryId: "sales",
    name: "Sales by Item",
    summary: "Item-wise sales values to identify top-selling products.",
    howItHelps: "Improve pricing, inventory, and campaigns based on item-level performance.",
    basis: "Accrual",
    source: "Invoices and Credit Notes",
    functionSupport: support("filter", "compare", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },
  {
    id: "sales-by-plan",
    categoryId: "sales",
    name: "Sales by Plan",
    summary: "Plan-level sales breakdown for subscription businesses.",
    howItHelps: "Find best-selling plans and optimize packaging and pricing decisions.",
    basis: "Accrual",
    source: "Invoices and Credit Notes",
    functionSupport: support("filter", "group", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },
  {
    id: "sales-by-addon",
    categoryId: "sales",
    name: "Sales by Addon",
    summary: "Addon-level sales contribution across customers.",
    howItHelps: "Find cross-sell opportunities and optimize addon bundles.",
    basis: "Accrual",
    source: "Invoices and Credit Notes",
    functionSupport: support("filter", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },
  {
    id: "sales-by-coupon",
    categoryId: "sales",
    name: "Sales by Coupon",
    summary: "Coupon usage, quantity sold, and total discount value.",
    howItHelps: "Measure coupon impact and optimize promotional strategy.",
    basis: "Accrual",
    source: "Invoices",
    functionSupport: support("filter", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },
  {
    id: "sales-by-sales-person",
    categoryId: "sales",
    name: "Sales by Sales Person",
    summary: "Sales summary by salesperson.",
    howItHelps: "Measure sales team contribution and drive target-based incentives.",
    basis: "Accrual",
    source: "Invoices and Credit Notes",
    functionSupport: support("filter", "compare", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },
  {
    id: "sales-summary",
    categoryId: "sales",
    name: "Sales Summary",
    summary: "Daily summary of invoices, credit notes, receipts, and total sales.",
    howItHelps: "Monitor daily trend movement and detect peaks or dips quickly.",
    basis: "Accrual",
    source: "Invoices, Credit Notes, Sales Receipts",
    functionSupport: support("filter", "group", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },

  {
    id: "ar-aging-summary",
    categoryId: "receivables",
    name: "AR Aging Summary",
    summary: "Customer-level outstanding amounts segmented by aging buckets.",
    howItHelps: "Prioritize collections by risk and overdue duration.",
    source: "Outstanding Invoices and Open Credit Notes",
    functionSupport: support("filter", "group", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },
  {
    id: "ar-aging-details",
    categoryId: "receivables",
    name: "AR Aging Details",
    summary: "Transaction-level overdue details across aging intervals.",
    howItHelps: "Drive targeted follow-up at invoice level.",
    source: "Outstanding Invoices and Open Credit Notes",
    functionSupport: support("filter", "group", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },
  {
    id: "invoice-details",
    categoryId: "receivables",
    name: "Invoice Details",
    summary: "Comprehensive invoice list for the selected period.",
    howItHelps: "Useful for audits, billing reviews, and customer or product-level analysis.",
    functionSupport: support("filter", "group", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },
  {
    id: "retainer-invoice-details",
    categoryId: "receivables",
    name: "Retainer Invoice Details",
    summary: "Retainer invoices and advanced payment tracking.",
    howItHelps: "Track liability-linked payments for future delivery.",
    functionSupport: support("filter", "group", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },
  {
    id: "quote-details",
    categoryId: "receivables",
    name: "Quote Details",
    summary: "Quote-level listing for follow-up and conversion workflows.",
    howItHelps: "Target unaccepted quotes for conversion recovery.",
    functionSupport: support("filter", "group", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },
  {
    id: "bad-debts",
    categoryId: "receivables",
    name: "Bad Debts",
    summary: "Invoices written off as uncollectible within period.",
    howItHelps: "Measure credit risk impact and improve credit policy.",
    functionSupport: support("filter", "sort", "schedule", "share", "export", "print"),
  },
  {
    id: "customer-balance-summary",
    categoryId: "receivables",
    name: "Customer Balance Summary",
    summary: "Consolidated receivable snapshot by customer.",
    howItHelps: "Quick account-level visibility without opening each transaction.",
    functionSupport: support("filter", "group", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },
  {
    id: "receivable-summary",
    categoryId: "receivables",
    name: "Receivable Summary",
    summary: "Summarized list of receivable transactions.",
    howItHelps: "Single view for status checks and audit readiness.",
    functionSupport: support("filter", "group", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },
  {
    id: "receivable-details",
    categoryId: "receivables",
    name: "Receivable Details",
    summary: "Item-level breakdown of receivable transactions.",
    howItHelps: "Drill into product-wise performance and receivable exposure.",
    functionSupport: support("filter", "group", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },
  {
    id: "progress-invoice-summary",
    categoryId: "receivables",
    name: "Progress Invoice Summary",
    summary: "Milestone billing status for estimates with progress invoices enabled.",
    howItHelps: "Track invoiced vs pending amount across project milestones.",
    functionSupport: support("filter", "group", "customizeColumns", "sort", "share", "export", "print"),
  },
  {
    id: "active-trials",
    categoryId: "acquisition-insights",
    name: "Active Trials",
    summary: "Subscriptions currently in trial state with trial state filters.",
    howItHelps: "Find trials about to expire and improve onboarding follow-up timing.",
    functionSupport: support("filter", "group", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },
  {
    id: "inactive-trials",
    categoryId: "acquisition-insights",
    name: "Inactive Trials",
    summary: "Trials that expired or were canceled in the selected period.",
    howItHelps: "Identify failed conversion cohorts and recover them with targeted action.",
    functionSupport: support("filter", "group", "sort", "schedule", "share", "export", "print", "custom"),
  },
  {
    id: "trial-to-live-conversions",
    categoryId: "acquisition-insights",
    name: "Trial to Live Conversions",
    summary: "Conversion movement from trial to live for the chosen period.",
    howItHelps: "Measure conversion efficiency and bottlenecks in the trial funnel.",
    formula: "Conversion Rate = (Trial Conversions / Eligible Trials) x 100",
    logicNotes: [
      "Eligible Trials should be the denominator for the same reporting frame.",
      "If include-cross-period is enabled, include conversions where trial started before the selected period.",
    ],
    calculator: {
      resultLabel: "Conversion Rate (%)",
      precision: 2,
      fields: [
        { key: "trial_conversions", label: "Trial Conversions", defaultValue: 24 },
        { key: "eligible_trials", label: "Eligible Trials", defaultValue: 80 },
      ],
      calculate: (inputs) => safeDivide(inputs.trial_conversions, inputs.eligible_trials) * 100,
    },
    functionSupport: support("filter", "group", "compare", "performance", "schedule", "share", "export"),
  },
  {
    id: "average-sales-cycle-length",
    categoryId: "acquisition-insights",
    name: "Average Sales Cycle Length",
    summary: "Average days from trial start to first payment.",
    howItHelps: "Reduce time-to-convert by refining onboarding and sales touchpoints.",
    functionSupport: support("filter", "group", "compare", "performance", "schedule", "share", "export"),
  },
  {
    id: "lost-opportunities",
    categoryId: "acquisition-insights",
    name: "Lost Opportunities",
    summary: "Potential customers who failed to sign up due to payment failures.",
    howItHelps: "Recover failed signups and fix gateway or payment journey issues.",
    functionSupport: support("filter", "schedule", "share", "export"),
  },

  {
    id: "signups",
    categoryId: "signups-activations",
    name: "Signups",
    summary: "Total new subscriptions created (including trial/free/future).",
    howItHelps: "Track acquisition momentum over time.",
    formula: "Signups = Total new subscriptions created in the period",
    functionSupport: support("filter", "group", "performance", "compare", "schedule", "share", "export"),
  },
  {
    id: "activations",
    categoryId: "signups-activations",
    name: "Activations",
    summary: "Total subscriptions moved to active status.",
    howItHelps: "Track real usage conversion, not just interest.",
    functionSupport: support("filter", "group", "performance", "compare", "schedule", "share", "export"),
  },
  {
    id: "activations-by-country",
    categoryId: "signups-activations",
    name: "Activations by Country",
    summary: "Country-wise active subscriptions by month.",
    howItHelps: "Measure geographic traction and regional sales effectiveness.",
    functionSupport: support("filter", "sort", "share", "export"),
  },

  {
    id: "net-revenue",
    categoryId: "revenue",
    name: "Net Revenue",
    summary: "Total invoice payments minus refunds in the same period.",
    howItHelps: "Track real revenue movement after refund leakage.",
    formula: "Net Revenue = Payments Received - Refunds",
    calculator: {
      resultLabel: "Net Revenue",
      precision: 2,
      fields: [
        { key: "payments_received", label: "Payments Received", defaultValue: 120000 },
        { key: "refunds", label: "Refunds", defaultValue: 8500 },
      ],
      calculate: (inputs) => inputs.payments_received - inputs.refunds,
    },
    functionSupport: support("filter", "group", "compare", "performance", "schedule", "share", "export"),
  },
  {
    id: "revenue-by-country",
    categoryId: "revenue",
    name: "Revenue by Country",
    summary: "Country-wise net revenue contribution after refunds.",
    howItHelps: "Find strongest and weakest regional markets.",
    functionSupport: support("filter", "sort", "share", "export"),
  },

  {
    id: "active-subscriptions",
    categoryId: "subscriptions",
    name: "Active Subscriptions",
    summary: "Active subscription count movement including activations/reactivations/cancellations.",
    howItHelps: "Monitor stability and growth of active base over time.",
    formula: "Active Subscriptions = Previous Active + Activations + Reactivations - Cancellations",
    calculator: {
      resultLabel: "Active Subscriptions",
      precision: 0,
      fields: [
        { key: "previous_active", label: "Previous Active", defaultValue: 420 },
        { key: "activations", label: "Activations", defaultValue: 38 },
        { key: "reactivations", label: "Reactivations", defaultValue: 6 },
        { key: "cancellations", label: "Cancellations", defaultValue: 22 },
      ],
      calculate: (inputs) => inputs.previous_active + inputs.activations + inputs.reactivations - inputs.cancellations,
    },
    functionSupport: support("filter", "compare", "group", "schedule", "share", "export"),
  },
  {
    id: "net-customers",
    categoryId: "subscriptions",
    name: "Net Customers",
    summary: "Net subscription change from activations/reactivations/cancellations.",
    howItHelps: "Quick signal for subscription growth or decline.",
    formula: "Net Customers = Activations + Reactivations - Cancellations",
    calculator: {
      resultLabel: "Net Customers",
      precision: 0,
      fields: [
        { key: "activations", label: "Activations", defaultValue: 130 },
        { key: "reactivations", label: "Reactivations", defaultValue: 14 },
        { key: "cancellations", label: "Cancellations", defaultValue: 59 },
      ],
      calculate: (inputs) => inputs.activations + inputs.reactivations - inputs.cancellations,
    },
    functionSupport: support("filter", "compare", "group", "schedule", "share", "export"),
  },
  {
    id: "subscription-details",
    categoryId: "subscriptions",
    name: "Subscription Details",
    summary: "Detailed subscription listing by selected date type.",
    howItHelps: "Audit subscriptions, billing milestones, and lifecycle state quickly.",
    functionSupport: support("filter", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },
  {
    id: "upgrades",
    categoryId: "subscriptions",
    name: "Upgrades",
    summary: "Subscriptions that moved to higher price/frequency plans.",
    howItHelps: "Track expansion behavior and promotion impact.",
    functionSupport: support("filter", "compare", "group", "schedule", "share"),
  },
  {
    id: "downgrades",
    categoryId: "subscriptions",
    name: "Downgrades",
    summary: "Subscriptions that moved to lower price/frequency plans.",
    howItHelps: "Detect contraction trends and retention risk areas.",
    functionSupport: support("filter", "compare", "group", "schedule", "share"),
  },
  {
    id: "subscription-summary",
    categoryId: "subscriptions",
    name: "Summary",
    summary: "Consolidated subscription movement metrics by period.",
    howItHelps: "One-screen tracking for acquisition, churn, upgrades, and net movement.",
    functionSupport: support("filter", "group", "schedule", "share", "export"),
  },
  {
    id: "arpu",
    categoryId: "subscriptions",
    name: "ARPU",
    summary: "Average revenue per active subscription.",
    howItHelps: "Measure monetization quality of your active base.",
    formula: "ARPU = Net MRR / Total Active Subscriptions",
    calculator: {
      resultLabel: "ARPU",
      precision: 2,
      fields: [
        { key: "net_mrr", label: "Net MRR", defaultValue: 84500 },
        { key: "active_subscriptions", label: "Active Subscriptions", defaultValue: 520 },
      ],
      calculate: (inputs) => safeDivide(inputs.net_mrr, inputs.active_subscriptions),
    },
    functionSupport: support("filter", "compare", "schedule", "share", "export"),
  },
  {
    id: "ltv",
    categoryId: "subscriptions",
    name: "LTV",
    summary: "Estimated long-term value of subscriptions based on ARPU and churn.",
    howItHelps: "Assess long-term revenue potential and acquisition affordability.",
    formula: "LTV = ARPU / Churn Rate (decimal). If churn is entered as %, LTV = (ARPU / Churn%) x 100",
    logicNotes: ["When churn is 0%, LTV is treated as 0 in Zoho Billing to avoid infinite projection."],
    calculator: {
      resultLabel: "LTV",
      precision: 2,
      fields: [
        { key: "arpu", label: "ARPU", defaultValue: 165.5 },
        { key: "churn_rate_percent", label: "Churn Rate (%)", defaultValue: 4.5 },
      ],
      calculate: (inputs) => (inputs.churn_rate_percent <= 0 ? 0 : (inputs.arpu / inputs.churn_rate_percent) * 100),
    },
    functionSupport: support("filter", "compare", "schedule", "share", "export"),
  },
  {
    id: "under-risk",
    categoryId: "churn",
    name: "Under Risk",
    summary: "Subscriptions in dunning due to payment failures.",
    howItHelps: "Fix payment failure causes before involuntary churn occurs.",
    functionSupport: support("filter", "customizeColumns", "sort", "schedule", "share", "export", "custom", "print"),
  },
  {
    id: "non-renewing-profiles",
    categoryId: "churn",
    name: "Non Renewing Profiles",
    summary: "Subscriptions scheduled to cancel in future dates.",
    howItHelps: "Run proactive save campaigns before cancellation date.",
    functionSupport: support("filter", "customizeColumns", "sort", "schedule", "share", "export", "custom", "print"),
  },
  {
    id: "churned-after-retries",
    categoryId: "churn",
    name: "Churned After Retries",
    summary: "Subscriptions canceled after dunning retries.",
    howItHelps: "Find retry failure patterns and fix payment operations.",
    functionSupport: support("filter", "customizeColumns", "sort", "schedule", "share", "export", "custom", "print"),
  },
  {
    id: "churned-subscriptions",
    categoryId: "churn",
    name: "Churned Subscriptions",
    summary: "Canceled subscriptions with reason and lifetime impact context.",
    howItHelps: "Understand causes of churn and prioritize win-back opportunities.",
    functionSupport: support("filter", "customizeColumns", "sort", "schedule", "share", "export", "custom", "print"),
  },
  {
    id: "subscription-expiry",
    categoryId: "churn",
    name: "Subscription Expiry",
    summary: "Subscriptions that expired or are expected to expire.",
    howItHelps: "Prepare renewal outreach and expiry-based retention workflows.",
    functionSupport: support("filter", "customizeColumns", "sort", "schedule", "share", "export", "custom", "print"),
  },

  {
    id: "net-cancellations",
    categoryId: "churn-insights",
    name: "Net Cancellations",
    summary: "Cancellations offset by reactivations.",
    howItHelps: "Measure retention health with one net metric.",
    formula: "Net Cancellations = Total Cancellations - Total Reactivations",
    calculator: {
      resultLabel: "Net Cancellations",
      precision: 0,
      fields: [
        { key: "cancellations", label: "Cancellations", defaultValue: 96 },
        { key: "reactivations", label: "Reactivations", defaultValue: 21 },
      ],
      calculate: (inputs) => inputs.cancellations - inputs.reactivations,
    },
    functionSupport: support("filter", "compare", "group", "schedule", "share", "export"),
  },
  {
    id: "churn-rate",
    categoryId: "churn-insights",
    name: "Churn Rate",
    summary: "Percentage of subscriptions canceled in a period.",
    howItHelps: "Track cancellation pressure and period-level churn trends.",
    formula: "Churn Rate = (Canceled Subscriptions / Subscriptions at Period Start) x 100",
    calculator: {
      resultLabel: "Churn Rate (%)",
      precision: 2,
      fields: [
        { key: "canceled_subscriptions", label: "Canceled Subscriptions", defaultValue: 43 },
        { key: "starting_subscriptions", label: "Starting Subscriptions", defaultValue: 680 },
      ],
      calculate: (inputs) => safeDivide(inputs.canceled_subscriptions, inputs.starting_subscriptions) * 100,
    },
    functionSupport: support("filter", "compare", "group", "schedule", "share", "export"),
  },
  {
    id: "revenue-churn",
    categoryId: "churn-insights",
    name: "Revenue Churn",
    summary: "Percentage of MRR lost due to churn (gross or net view).",
    howItHelps: "Measure recurring revenue leakage and recovery effectiveness.",
    formula: "Gross Revenue Churn = (Churn MRR / Previous MRR) x 100; Net Revenue Churn = ((Churn MRR - Expansion MRR) / Previous MRR) x 100",
    calculator: {
      resultLabel: "Net Revenue Churn (%)",
      precision: 2,
      fields: [
        { key: "churn_mrr", label: "Churn MRR", defaultValue: 9200 },
        { key: "expansion_mrr", label: "Expansion MRR", defaultValue: 3400 },
        { key: "previous_mrr", label: "Previous MRR", defaultValue: 110000 },
      ],
      calculate: (inputs) => safeDivide(inputs.churn_mrr - inputs.expansion_mrr, inputs.previous_mrr) * 100,
      helpText: "Use Gross mode by setting Expansion MRR to 0.",
    },
    functionSupport: support("filter", "compare", "schedule", "share", "export"),
  },

  {
    id: "payments-received",
    categoryId: "payments-received",
    name: "Payments Received",
    summary: "List of all customer payments by transaction type and product.",
    howItHelps: "Track realized cash inflow and validate payment status quickly.",
    functionSupport: support("filter", "group", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },
  {
    id: "time-to-get-paid",
    categoryId: "payments-received",
    name: "Time to Get Paid",
    summary: "Receivables expected by upcoming aging intervals.",
    howItHelps: "Plan collection efforts based on near-term due windows.",
    functionSupport: support("filter", "group", "customizeColumns", "sort", "share", "export", "print", "custom"),
  },
  {
    id: "credit-note-details",
    categoryId: "payments-received",
    name: "Credit Note Details",
    summary: "Credit notes raised with status and filter options.",
    howItHelps: "Monitor credit issuance and prevent unnoticed revenue leakage.",
    functionSupport: support("filter", "group", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },
  {
    id: "refund-history",
    categoryId: "payments-received",
    name: "Refund History",
    summary: "Refund and credit-note refund transactions in one view.",
    howItHelps: "Audit refund flows and investigate anomalies faster.",
    functionSupport: support("filter", "group", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },
  {
    id: "payment-failures",
    categoryId: "payments-received",
    name: "Payment Failures",
    summary: "Failure count trend and detailed failed renewal attempts.",
    howItHelps: "Reduce failed renewals through gateway and customer remediation.",
    functionSupport: support("filter", "group", "sort", "schedule", "share", "export"),
  },
  {
    id: "card-expiry",
    categoryId: "payments-received",
    name: "Card Expiry",
    summary: "Cards already expired or expiring soon.",
    howItHelps: "Trigger card update reminders before renewal failures occur.",
    functionSupport: support("filter", "group", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },

  {
    id: "expense-details",
    categoryId: "purchases-expenses",
    name: "Expense Details",
    summary: "Detailed list of expenses and total incurred amount.",
    howItHelps: "Track spend directly and validate each expense line.",
    functionSupport: support("filter", "group", "customizeColumns", "sort", "share", "export", "print"),
  },
  {
    id: "expenses-by-category",
    categoryId: "purchases-expenses",
    name: "Expenses by Category",
    summary: "Category-level expense summary and totals.",
    howItHelps: "Find major spend drivers and optimize cost controls.",
    functionSupport: support("filter", "sort", "share", "export", "print"),
  },
  {
    id: "expenses-by-customer",
    categoryId: "purchases-expenses",
    name: "Expenses by Customers",
    summary: "Expense distribution and totals by customer.",
    howItHelps: "Understand customer-level profitability pressure.",
    functionSupport: support("filter", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },
  {
    id: "expenses-by-project",
    categoryId: "purchases-expenses",
    name: "Expenses by Projects",
    summary: "Project-wise expense totals and contribution.",
    howItHelps: "Track project profitability and budget pressure.",
    functionSupport: support("filter", "group", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },
  {
    id: "billable-expense-details",
    categoryId: "purchases-expenses",
    name: "Billable Expense Details",
    summary: "Billable expenses with invoiced amount and status context.",
    howItHelps: "Reduce missed billing and improve expense recovery.",
    functionSupport: support("filter", "group", "customizeColumns", "sort", "schedule", "share", "export", "print"),
  },

  {
    id: "timesheet-details",
    categoryId: "projects-timesheets",
    name: "Timesheet Details",
    summary: "Timesheet entries with billed/unbilled and billable/non-billable split.",
    howItHelps: "Improve utilization visibility and billing completeness.",
    functionSupport: support("filter", "group", "schedule", "share", "export", "print"),
  },
  {
    id: "project-summary",
    categoryId: "projects-timesheets",
    name: "Project Summary",
    summary: "Project-level summary including logged and billed context.",
    howItHelps: "Fast operational review of ongoing and completed projects.",
    functionSupport: support("filter", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },
  {
    id: "projects-revenue-summary",
    categoryId: "projects-timesheets",
    name: "Projects Revenue Summary",
    summary: "Project budget amount vs actual earned revenue.",
    howItHelps: "Compare budget expectations against realized revenue.",
    functionSupport: support("filter", "customizeColumns", "sort", "schedule", "share", "export", "print", "custom"),
  },

  {
    id: "system-mails",
    categoryId: "activity",
    name: "System Mails",
    summary: "Organization email activity across mail types.",
    howItHelps: "Audit outbound communication and operational consistency.",
    functionSupport: support("filter", "customizeColumns", "sort", "share", "export", "print"),
  },
  {
    id: "activity-logs-audit-trail",
    categoryId: "activity",
    name: "Activity Logs and Audit Trail",
    summary: "System activity with versioned audit comparisons.",
    howItHelps: "Track who changed what and when for compliance and debugging.",
    functionSupport: support("filter", "customizeColumns", "sort", "schedule", "share", "export", "print"),
  },
  {
    id: "portal-activities",
    categoryId: "activity",
    name: "Portal Activities",
    summary: "Customer portal usage and behavior logs.",
    howItHelps: "Understand portal engagement and self-service behavior.",
    functionSupport: support("filter", "customizeColumns", "sort", "share", "export", "print"),
  },
  {
    id: "customer-reviews",
    categoryId: "activity",
    name: "Customer Reviews",
    summary: "Ratings summary and review-level listing.",
    howItHelps: "Identify detractor cohorts and improve customer experience.",
    functionSupport: support("filter", "customizeColumns", "sort", "schedule", "share", "export", "print"),
  },

  {
    id: "mrr",
    categoryId: "mrr-arr",
    name: "Monthly Recurring Revenue (MRR)",
    summary: "Recurring monthly revenue with expansion, contraction, and churn components.",
    howItHelps: "Core SaaS growth metric for recurring revenue trajectory.",
    formula: "Net MRR = Previous MRR + (New MRR + Expansion MRR + Reactivation MRR - Contraction MRR - Churn MRR)",
    calculator: {
      resultLabel: "Net MRR",
      precision: 2,
      fields: [
        { key: "previous_mrr", label: "Previous MRR", defaultValue: 132000 },
        { key: "new_mrr", label: "New MRR", defaultValue: 14500 },
        { key: "expansion_mrr", label: "Expansion MRR", defaultValue: 6200 },
        { key: "reactivation_mrr", label: "Reactivation MRR", defaultValue: 1800 },
        { key: "contraction_mrr", label: "Contraction MRR", defaultValue: 2400 },
        { key: "churn_mrr", label: "Churn MRR", defaultValue: 5300 },
      ],
      calculate: (inputs) =>
        inputs.previous_mrr + (inputs.new_mrr + inputs.expansion_mrr + inputs.reactivation_mrr - inputs.contraction_mrr - inputs.churn_mrr),
    },
    functionSupport: support("filter", "compare", "schedule", "share", "export"),
  },
  {
    id: "arr",
    categoryId: "mrr-arr",
    name: "Annual Recurring Revenue (ARR)",
    summary: "Predicted annual recurring revenue based on monthly run rate.",
    howItHelps: "Long-term recurring revenue projection and valuation support.",
    formula: "ARR = MRR x 12",
    calculator: {
      resultLabel: "ARR",
      precision: 2,
      fields: [{ key: "mrr", label: "MRR", defaultValue: 146800 }],
      calculate: (inputs) => inputs.mrr * 12,
    },
    functionSupport: support("filter", "compare", "schedule", "share", "export"),
  },
  {
    id: "mrr-quick-ratio",
    categoryId: "mrr-arr",
    name: "MRR Quick Ratio",
    summary: "Growth MRR relative to lost MRR.",
    howItHelps: "Quick test of whether recurring growth outpaces losses.",
    formula: "MRR Quick Ratio = (New MRR + Expansion MRR) / (Contraction MRR + Churn MRR)",
    calculator: {
      resultLabel: "MRR Quick Ratio",
      precision: 2,
      fields: [
        { key: "new_mrr", label: "New MRR", defaultValue: 12000 },
        { key: "expansion_mrr", label: "Expansion MRR", defaultValue: 3900 },
        { key: "contraction_mrr", label: "Contraction MRR", defaultValue: 2400 },
        { key: "churn_mrr", label: "Churn MRR", defaultValue: 2900 },
      ],
      calculate: (inputs) => safeDivide(inputs.new_mrr + inputs.expansion_mrr, inputs.contraction_mrr + inputs.churn_mrr),
      helpText: "Values > 1 mean growth MRR is greater than loss MRR.",
    },
    functionSupport: support("filter", "compare", "share"),
  },
];

export const REPORTS_BY_CATEGORY = REPORT_CATEGORIES.reduce((acc, category) => {
  acc[category.id] = REPORTS.filter((report) => report.categoryId === category.id);
  return acc;
}, {} as Record<string, ReportDefinition[]>);

export const getCategoryById = (id: string) => REPORT_CATEGORIES.find((category) => category.id === id);

export const getReportById = (categoryId: string, reportId: string) =>
  REPORTS.find((report) => report.categoryId === categoryId && report.id === reportId);
