export type SelectOption = { value: string; label: string };

export const TIME_ZONES: SelectOption[] = [
  { value: 'Etc/GMT+12', label: '(GMT -12:00) GMT-12:00 (Etc/GMT+12)' },
  { value: 'Etc/GMT+11', label: '(GMT -11:00) GMT-11:00 (Etc/GMT+11)' },
  { value: 'MIT', label: '(GMT -11:00) West Samoa Time (MIT)' },
  { value: 'Pacific/Apia', label: '(GMT -11:00) West Samoa Time (Pacific/Apia)' },
  { value: 'Pacific/Midway', label: '(GMT -11:00) Samoa Standard Time (Pacific/Midway)' },
  { value: 'Pacific/Niue', label: '(GMT -11:00) Niue Time (Pacific/Niue)' },
  { value: 'Pacific/Pago_Pago', label: '(GMT -11:00) Samoa Standard Time (Pacific/Pago_Pago)' },
  { value: 'Pacific/Samoa', label: '(GMT -11:00) Samoa Standard Time (Pacific/Samoa)' },
  { value: 'US/Samoa', label: '(GMT -11:00) Samoa Standard Time (US/Samoa)' },
  { value: 'America/Adak', label: '(GMT -10:00) Hawaii-Aleutian Daylight Time (America/Adak)' },
  { value: 'America/Atka', label: '(GMT -10:00) Hawaii-Aleutian Daylight Time (America/Atka)' },
  { value: 'Etc/GMT+10', label: '(GMT -10:00) GMT-10:00 (Etc/GMT+10)' },
  { value: 'HST', label: '(GMT -10:00) Hawaii Standard Time (HST)' },
  { value: 'Pacific/Fakaofo', label: '(GMT -10:00) Tokelau Time (Pacific/Fakaofo)' },
  { value: 'Pacific/Honolulu', label: '(GMT -10:00) Hawaii Standard Time (Pacific/Honolulu)' },
  { value: 'Pacific/Johnston', label: '(GMT -10:00) Hawaii Standard Time (Pacific/Johnston)' },
  { value: 'Pacific/Rarotonga', label: '(GMT -10:00) Cook Is. Time (Pacific/Rarotonga)' },
  { value: 'Pacific/Tahiti', label: '(GMT -10:00) Tahiti Time (Pacific/Tahiti)' },
  { value: 'SystemV/HST10', label: '(GMT -10:00) Hawaii Standard Time (SystemV/HST10)' },
  { value: 'US/Aleutian', label: '(GMT -10:00) Hawaii-Aleutian Daylight Time (US/Aleutian)' },
  { value: 'US/Hawaii', label: '(GMT -10:00) Hawaii Standard Time (US/Hawaii)' },
  { value: 'Pacific/Marquesas', label: '(GMT -9:30) Marquesas Time (Pacific/Marquesas)' },
  { value: 'AST', label: '(GMT -9:00) Alaska Daylight Time (AST)' },
  { value: 'America/Anchorage', label: '(GMT -9:00) Alaska Daylight Time (America/Anchorage)' },
  { value: 'America/Juneau', label: '(GMT -9:00) Alaska Daylight Time (America/Juneau)' },
  { value: 'America/Nome', label: '(GMT -9:00) Alaska Daylight Time (America/Nome)' },
  { value: 'America/Yakutat', label: '(GMT -9:00) Alaska Daylight Time (America/Yakutat)' },
  { value: 'Etc/GMT+9', label: '(GMT -9:00) GMT-09:00 (Etc/GMT+9)' },
  { value: 'Pacific/Gambier', label: '(GMT -9:00) Gambier Time (Pacific/Gambier)' },
  { value: 'SystemV/YST9', label: '(GMT -9:00) Alaska Standard Time (SystemV/YST9)' },
  { value: 'SystemV/YST9YDT', label: '(GMT -9:00) Alaska Daylight Time (SystemV/YST9YDT)' },
  { value: 'US/Alaska', label: '(GMT -9:00) Alaska Daylight Time (US/Alaska)' },
  { value: 'America/Dawson', label: '(GMT -8:00) Pacific Daylight Time (America/Dawson)' },
  { value: 'America/Ensenada', label: '(GMT -8:00) Pacific Daylight Time (America/Ensenada)' },
  { value: 'America/Los_Angeles', label: '(GMT -8:00) Pacific Daylight Time (America/Los_Angeles)' },
  { value: 'America/Tijuana', label: '(GMT -8:00) Pacific Daylight Time (America/Tijuana)' },
  { value: 'America/Vancouver', label: '(GMT -8:00) Pacific Daylight Time (America/Vancouver)' },
  { value: 'America/Whitehorse', label: '(GMT -8:00) Pacific Daylight Time (America/Whitehorse)' },
  { value: 'Canada/Pacific', label: '(GMT -8:00) Pacific Daylight Time (Canada/Pacific)' },
  { value: 'Canada/Yukon', label: '(GMT -8:00) Pacific Daylight Time (Canada/Yukon)' },
  { value: 'Etc/GMT+8', label: '(GMT -8:00) GMT-08:00 (Etc/GMT+8)' },
  { value: 'Mexico/BajaNorte', label: '(GMT -8:00) Pacific Daylight Time (Mexico/BajaNorte)' },
  { value: 'PST', label: '(GMT -8:00) Pacific Daylight Time (PST)' },
  { value: 'PST8PDT', label: '(GMT -8:00) Pacific Daylight Time (PST8PDT)' },
  { value: 'Pacific/Pitcairn', label: '(GMT -8:00) Pitcairn Standard Time (Pacific/Pitcairn)' },
  { value: 'SystemV/PST8', label: '(GMT -8:00) Pacific Standard Time (SystemV/PST8)' },
  { value: 'SystemV/PST8PDT', label: '(GMT -8:00) Pacific Daylight Time (SystemV/PST8PDT)' },
  { value: 'US/Pacific', label: '(GMT -8:00) Pacific Daylight Time (US/Pacific)' },
  { value: 'US/Pacific-New', label: '(GMT -8:00) Pacific Daylight Time (US/Pacific-New)' },
  { value: 'America/Boise', label: '(GMT -7:00) Mountain Daylight Time (America/Boise)' },
  { value: 'America/Cambridge_Bay', label: '(GMT -7:00) Mountain Daylight Time (America/Cambridge_Bay)' },
  { value: 'America/Chihuahua', label: '(GMT -7:00) Mountain Daylight Time (America/Chihuahua)' },
  { value: 'America/Dawson_Creek', label: '(GMT -7:00) Mountain Standard Time (America/Dawson_Creek)' },
  { value: 'America/Denver', label: '(GMT -7:00) Mountain Daylight Time (America/Denver)' },
  { value: 'America/Edmonton', label: '(GMT -7:00) Mountain Daylight Time (America/Edmonton)' },
  { value: 'America/Hermosillo', label: '(GMT -7:00) Mountain Standard Time (America/Hermosillo)' },
  { value: 'America/Inuvik', label: '(GMT -7:00) Mountain Daylight Time (America/Inuvik)' },
  { value: 'America/Mazatlan', label: '(GMT -7:00) Mountain Daylight Time (America/Mazatlan)' },
  { value: 'America/Phoenix', label: '(GMT -7:00) Mountain Standard Time (America/Phoenix)' },
  { value: 'America/Shiprock', label: '(GMT -7:00) Mountain Daylight Time (America/Shiprock)' },
  { value: 'America/Yellowknife', label: '(GMT -7:00) Mountain Daylight Time (America/Yellowknife)' },
  { value: 'Canada/Mountain', label: '(GMT -7:00) Mountain Daylight Time (Canada/Mountain)' },
  { value: 'Etc/GMT+7', label: '(GMT -7:00) GMT-07:00 (Etc/GMT+7)' },
  { value: 'MST', label: '(GMT -7:00) Mountain Standard Time (MST)' },
  { value: 'MST7MDT', label: '(GMT -7:00) Mountain Daylight Time (MST7MDT)' },
  { value: 'Mexico/BajaSur', label: '(GMT -7:00) Mountain Daylight Time (Mexico/BajaSur)' },
  { value: 'Navajo', label: '(GMT -7:00) Mountain Daylight Time (Navajo)' },
  { value: 'PNT', label: '(GMT -7:00) Mountain Standard Time (PNT)' },
  { value: 'SystemV/MST7', label: '(GMT -7:00) Mountain Standard Time (SystemV/MST7)' },
  { value: 'SystemV/MST7MDT', label: '(GMT -7:00) Mountain Daylight Time (SystemV/MST7MDT)' },
  { value: 'US/Arizona', label: '(GMT -7:00) Mountain Standard Time (US/Arizona)' },
  { value: 'US/Mountain', label: '(GMT -7:00) Mountain Daylight Time (US/Mountain)' },
  { value: 'America/Belize', label: '(GMT -6:00) Central Standard Time (America/Belize)' },
  { value: 'America/Cancun', label: '(GMT -6:00) Central Daylight Time (America/Cancun)' },
  { value: 'America/Chicago', label: '(GMT -6:00) Central Daylight Time (America/Chicago)' },
  { value: 'America/Costa_Rica', label: '(GMT -6:00) Central Standard Time (America/Costa_Rica)' },
  { value: 'America/El_Salvador', label: '(GMT -6:00) Central Standard Time (America/El_Salvador)' },
  { value: 'America/Guatemala', label: '(GMT -6:00) Central Standard Time (America/Guatemala)' },
  { value: 'America/Indiana/Knox', label: '(GMT -6:00) Central Daylight Time (America/Indiana/Knox)' },
  { value: 'America/Indiana/Petersburg', label: '(GMT -6:00) Central Daylight Time (America/Indiana/Petersburg)' },
  { value: 'America/Indiana/Vincennes', label: '(GMT -6:00) Central Daylight Time (America/Indiana/Vincennes)' },
  { value: 'America/Knox_IN', label: '(GMT -6:00) Eastern Daylight Time (America/Knox_IN)' },
  { value: 'America/Managua', label: '(GMT -6:00) Central Standard Time (America/Managua)' },
  { value: 'America/Menominee', label: '(GMT -6:00) Central Daylight Time (America/Menominee)' },
  { value: 'America/Merida', label: '(GMT -6:00) Central Daylight Time (America/Merida)' },
  { value: 'America/Mexico_City', label: '(GMT -6:00) Central Daylight Time (America/Mexico_City)' },
  { value: 'America/Monterrey', label: '(GMT -6:00) Central Daylight Time (America/Monterrey)' },
  { value: 'America/North_Dakota/Center', label: '(GMT -6:00) Central Daylight Time (America/North_Dakota/Center)' },
  { value: 'America/North_Dakota/New_Salem', label: '(GMT -6:00) Central Daylight Time (America/North_Dakota/New_Salem)' },
  { value: 'America/Rainy_River', label: '(GMT -6:00) Central Daylight Time (America/Rainy_River)' },
  { value: 'America/Rankin_Inlet', label: '(GMT -6:00) Central Daylight Time (America/Rankin_Inlet)' },
  { value: 'America/Regina', label: '(GMT -6:00) Central Standard Time (America/Regina)' },
  { value: 'America/Swift_Current', label: '(GMT -6:00) Central Standard Time (America/Swift_Current)' },
  { value: 'America/Tegucigalpa', label: '(GMT -6:00) Central Standard Time (America/Tegucigalpa)' },
  { value: 'America/Winnipeg', label: '(GMT -6:00) Central Daylight Time (America/Winnipeg)' },
  { value: 'CST', label: '(GMT -6:00) Central Daylight Time (CST)' },
  { value: 'CST6CDT', label: '(GMT -6:00) Central Daylight Time (CST6CDT)' },
  { value: 'Canada/Central', label: '(GMT -6:00) Central Daylight Time (Canada/Central)' },
  { value: 'Canada/East-Saskatchewan', label: '(GMT -6:00) Central Standard Time (Canada/East-Saskatchewan)' },
  { value: 'Canada/Saskatchewan', label: '(GMT -6:00) Central Standard Time (Canada/Saskatchewan)' },
  { value: 'Chile/EasterIsland', label: '(GMT -6:00) Easter Is. Time (Chile/EasterIsland)' },
  { value: 'Etc/GMT+6', label: '(GMT -6:00) GMT-06:00 (Etc/GMT+6)' },
  { value: 'Mexico/General', label: '(GMT -6:00) Central Daylight Time (Mexico/General)' },
  { value: 'Pacific/Easter', label: '(GMT -6:00) Easter Is. Time (Pacific/Easter)' },
  { value: 'Pacific/Galapagos', label: '(GMT -6:00) Galapagos Time (Pacific/Galapagos)' },
  { value: 'SystemV/CST6', label: '(GMT -6:00) Central Standard Time (SystemV/CST6)' },
  { value: 'SystemV/CST6CDT', label: '(GMT -6:00) Central Daylight Time (SystemV/CST6CDT)' },
  { value: 'US/Central', label: '(GMT -6:00) Central Daylight Time (US/Central)' },
  { value: 'US/Indiana-Starke', label: '(GMT -6:00) Eastern Daylight Time (US/Indiana-Starke)' },
  { value: 'America/Atikokan', label: '(GMT -5:00) Eastern Standard Time (America/Atikokan)' },
  { value: 'America/Bogota', label: '(GMT -5:00) Colombia Time (America/Bogota)' },
  { value: 'America/Cayman', label: '(GMT -5:00) Eastern Standard Time (America/Cayman)' },
  { value: 'America/Coral_Harbour', label: '(GMT -5:00) Eastern Standard Time (America/Coral_Harbour)' },
  { value: 'America/Detroit', label: '(GMT -5:00) Eastern Daylight Time (America/Detroit)' },
  { value: 'America/Eirunepe', label: '(GMT -5:00) Acre Time (America/Eirunepe)' },
  { value: 'America/Fort_Wayne', label: '(GMT -5:00) Eastern Daylight Time (America/Fort_Wayne)' },
  { value: 'America/Grand_Turk', label: '(GMT -5:00) Eastern Daylight Time (America/Grand_Turk)' },
  { value: 'America/Guayaquil', label: '(GMT -5:00) Ecuador Time (America/Guayaquil)' },
  { value: 'America/Havana', label: '(GMT -5:00) Central Daylight Time (America/Havana)' },
  { value: 'America/Indiana/Indianapolis', label: '(GMT -5:00) Eastern Daylight Time (America/Indiana/Indianapolis)' },
  { value: 'America/Indiana/Marengo', label: '(GMT -5:00) Eastern Daylight Time (America/Indiana/Marengo)' },
  { value: 'America/Indiana/Vevay', label: '(GMT -5:00) Eastern Daylight Time (America/Indiana/Vevay)' },
  { value: 'America/Indianapolis', label: '(GMT -5:00) Eastern Daylight Time (America/Indianapolis)' },
  { value: 'America/Iqaluit', label: '(GMT -5:00) Eastern Daylight Time (America/Iqaluit)' },
  { value: 'America/Jamaica', label: '(GMT -5:00) Eastern Standard Time (America/Jamaica)' },
  { value: 'America/Kentucky/Louisville', label: '(GMT -5:00) Eastern Daylight Time (America/Kentucky/Louisville)' },
  { value: 'America/Kentucky/Monticello', label: '(GMT -5:00) Eastern Daylight Time (America/Kentucky/Monticello)' },
  { value: 'America/Lima', label: '(GMT -5:00) Peru Time (America/Lima)' },
  { value: 'America/Louisville', label: '(GMT -5:00) Eastern Daylight Time (America/Louisville)' },
  { value: 'America/Matamoros', label: '(GMT -5:00) Central Daylight Time (America/Matamoros)' },
  { value: 'America/Montreal', label: '(GMT -5:00) Eastern Daylight Time (America/Montreal)' },
  { value: 'America/Nassau', label: '(GMT -5:00) Eastern Daylight Time (America/Nassau)' },
  { value: 'America/New_York', label: '(GMT -5:00) Eastern Daylight Time (America/New_York)' },
  { value: 'America/Nipigon', label: '(GMT -5:00) Eastern Daylight Time (America/Nipigon)' },
  { value: 'America/Panama', label: '(GMT -5:00) Eastern Standard Time (America/Panama)' },
  { value: 'America/Pangnirtung', label: '(GMT -5:00) Eastern Daylight Time (America/Pangnirtung)' },
  { value: 'America/Port-au-Prince', label: '(GMT -5:00) Eastern Daylight Time (America/Port-au-Prince)' },
  { value: 'America/Porto_Acre', label: '(GMT -5:00) Acre Time (America/Porto_Acre)' },
  { value: 'America/Rio_Branco', label: '(GMT -5:00) Acre Time (America/Rio_Branco)' },
  { value: 'America/Thunder_Bay', label: '(GMT -5:00) Eastern Daylight Time (America/Thunder_Bay)' },
  { value: 'America/Toronto', label: '(GMT -5:00) Eastern Daylight Time (America/Toronto)' },
  { value: 'Brazil/Acre', label: '(GMT -5:00) Acre Time (Brazil/Acre)' },
  { value: 'Canada/Eastern', label: '(GMT -5:00) Eastern Daylight Time (Canada/Eastern)' },
  { value: 'Cuba', label: '(GMT -5:00) Central Daylight Time (Cuba)' },
  { value: 'EST', label: '(GMT -5:00) Eastern Standard Time (EST)' },
  { value: 'EST5EDT', label: '(GMT -5:00) Eastern Daylight Time (EST5EDT)' },
  { value: 'Etc/GMT+5', label: '(GMT -5:00) GMT-05:00 (Etc/GMT+5)' },
  { value: 'IET', label: '(GMT -5:00) Eastern Daylight Time (IET)' },
  { value: 'Jamaica', label: '(GMT -5:00) Eastern Standard Time (Jamaica)' },
  { value: 'SystemV/EST5', label: '(GMT -5:00) Eastern Standard Time (SystemV/EST5)' },
  { value: 'SystemV/EST5EDT', label: '(GMT -5:00) Eastern Daylight Time (SystemV/EST5EDT)' },
  { value: 'US/East-Indiana', label: '(GMT -5:00) Eastern Daylight Time (US/East-Indiana)' },
  { value: 'US/Eastern', label: '(GMT -5:00) Eastern Daylight time (US/Eastern)' },
  { value: 'US/Michigan', label: '(GMT -5:00) Eastern Daylight Time (US/Michigan)' },
  { value: 'America/Anguilla', label: '(GMT -4:00) Atlantic Standard Time (America/Anguilla)' },
  { value: 'America/Antigua', label: '(GMT -4:00) Atlantic Standard Time (America/Antigua)' },
  { value: 'America/Aruba', label: '(GMT -4:00) Atlantic Standard Time (America/Aruba)' },
  { value: 'America/Asuncion', label: '(GMT -4:00) Paraguay Time (America/Asuncion)' },
  { value: 'America/Barbados', label: '(GMT -4:00) Atlantic Standard Time (America/Barbados)' },
  { value: 'America/Blanc-Sablon', label: '(GMT -4:00) Atlantic Standard Time (America/Blanc-Sablon)' },
  { value: 'America/Boa_Vista', label: '(GMT -4:00) Amazon Time (America/Boa_Vista)' },
  { value: 'America/Campo_Grande', label: '(GMT -4:00) Amazon Time (America/Campo_Grande)' },
  { value: 'America/Caracas', label: '(GMT -4:00) Venezuela Time (America/Caracas)' },
  { value: 'America/Cuiaba', label: '(GMT -4:00) Amazon Time (America/Cuiaba)' },
  { value: 'America/Curacao', label: '(GMT -4:00) Atlantic Standard Time (America/Curacao)' },
  { value: 'America/Dominica', label: '(GMT -4:00) Atlantic Standard Time (America/Dominica)' },
  { value: 'America/Glace_Bay', label: '(GMT -4:00) Atlantic Daylight Time (America/Glace_Bay)' },
  { value: 'America/Goose_Bay', label: '(GMT -4:00) Atlantic Daylight Time (America/Goose_Bay)' },
  { value: 'America/Grenada', label: '(GMT -4:00) Atlantic Standard Time (America/Grenada)' },
  { value: 'America/Guadeloupe', label: '(GMT -4:00) Atlantic Standard Time (America/Guadeloupe)' },
  { value: 'America/Guyana', label: '(GMT -4:00) Guyana Time (America/Guyana)' },
  { value: 'America/Halifax', label: '(GMT -4:00) Atlantic Daylight Time (America/Halifax)' },
  { value: 'America/La_Paz', label: '(GMT -4:00) Bolivia Time (America/La_Paz)' },
  { value: 'America/Manaus', label: '(GMT -4:00) Amazon Time (America/Manaus)' },
  { value: 'America/Martinique', label: '(GMT -4:00) Atlantic Standard Time (America/Martinique)' },
  { value: 'America/Moncton', label: '(GMT -4:00) Atlantic Daylight Time (America/Moncton)' },
  { value: 'America/Montserrat', label: '(GMT -4:00) Atlantic Standard Time (America/Montserrat)' },
  { value: 'America/Port_of_Spain', label: '(GMT -4:00) Atlantic Standard Time (America/Port_of_Spain)' },
  { value: 'America/Porto_Velho', label: '(GMT -4:00) Amazon Time (America/Porto_Velho)' },
  { value: 'America/Puerto_Rico', label: '(GMT -4:00) Atlantic Standard Time (America/Puerto_Rico)' },
  { value: 'America/Santiago', label: '(GMT -4:00) Chile Time (America/Santiago)' },
  { value: 'America/Santo_Domingo', label: '(GMT -4:00) Atlantic Standard Time (America/Santo_Domingo)' },
  { value: 'America/St_Kitts', label: '(GMT -4:00) Atlantic Standard Time (America/St_Kitts)' },
  { value: 'America/St_Lucia', label: '(GMT -4:00) Atlantic Standard Time (America/St_Lucia)' },
  { value: 'America/St_Thomas', label: '(GMT -4:00) Atlantic Standard Time (America/St_Thomas)' },
  { value: 'America/St_Vincent', label: '(GMT -4:00) Atlantic Standard Time (America/St_Vincent)' },
  { value: 'America/Thule', label: '(GMT -4:00) Atlantic Daylight Time (America/Thule)' },
  { value: 'America/Tortola', label: '(GMT -4:00) Atlantic Standard Time (America/Tortola)' },
  { value: 'America/Virgin', label: '(GMT -4:00) Atlantic Standard Time (America/Virgin)' },
  { value: 'Antarctica/Palmer', label: '(GMT -4:00) Chile Time (Antarctica/Palmer)' },
  { value: 'Atlantic/Bermuda', label: '(GMT -4:00) Atlantic Daylight Time (Atlantic/Bermuda)' },
  { value: 'Atlantic/Stanley', label: '(GMT -4:00) Falkland Is. Summer Time (Atlantic/Stanley)' },
  { value: 'Brazil/West', label: '(GMT -4:00) Amazon Time (Brazil/West)' },
  { value: 'Canada/Atlantic', label: '(GMT -4:00) Atlantic Daylight Time (Canada/Atlantic)' },
  { value: 'Chile/Continental', label: '(GMT -4:00) Chile Time (Chile/Continental)' },
  { value: 'Etc/GMT+4', label: '(GMT -4:00) GMT-04:00 (Etc/GMT+4)' },
  { value: 'PRT', label: '(GMT -4:00) Atlantic Standard Time (PRT)' },
  { value: 'SystemV/AST4', label: '(GMT -4:00) Atlantic Standard Time (SystemV/AST4)' },
  { value: 'SystemV/AST4ADT', label: '(GMT -4:00) Atlantic Daylight Time (SystemV/AST4ADT)' },
  { value: 'America/St_Johns', label: '(GMT -3:30) Newfoundland Daylight Time (America/St_Johns)' },
  { value: 'CNT', label: '(GMT -3:30) Newfoundland Daylight Time (CNT)' },
  { value: 'Canada/Newfoundland', label: '(GMT -3:30) Newfoundland Daylight Time (Canada/Newfoundland)' },
  { value: 'AGT', label: '(GMT -3:00) Argentine Time (AGT)' },
  { value: 'America/Araguaina', label: '(GMT -3:00) Brasilia Time (America/Araguaina)' },
  { value: 'America/Argentina/Buenos_Aires', label: '(GMT -3:00) Argentine Time (America/Argentina/Buenos_Aires)' },
  { value: 'America/Argentina/Catamarca', label: '(GMT -3:00) Argentine Time (America/Argentina/Catamarca)' },
  { value: 'America/Argentina/ComodRivadavia', label: '(GMT -3:00) Argentine Time (America/Argentina/ComodRivadavia)' },
  { value: 'America/Argentina/Cordoba', label: '(GMT -3:00) Argentine Time (America/Argentina/Cordoba)' },
  { value: 'America/Argentina/Jujuy', label: '(GMT -3:00) Argentine Time (America/Argentina/Jujuy)' },
  { value: 'America/Argentina/La_Rioja', label: '(GMT -3:00) Argentine Time (America/Argentina/La_Rioja)' },
  { value: 'America/Argentina/Mendoza', label: '(GMT -3:00) Argentine Time (America/Argentina/Mendoza)' },
  { value: 'America/Argentina/Rio_Gallegos', label: '(GMT -3:00) Argentine Time (America/Argentina/Rio_Gallegos)' },
  { value: 'America/Argentina/San_Juan', label: '(GMT -3:00) Argentine Time (America/Argentina/San_Juan)' },
  { value: 'America/Argentina/Tucuman', label: '(GMT -3:00) Argentine Time (America/Argentina/Tucuman)' },
  { value: 'America/Argentina/Ushuaia', label: '(GMT -3:00) Argentine Time (America/Argentina/Ushuaia)' },
  { value: 'America/Bahia', label: '(GMT -3:00) Brasilia Time (America/Bahia)' },
  { value: 'America/Belem', label: '(GMT -3:00) Brasilia Time (America/Belem)' },
  { value: 'America/Buenos_Aires', label: '(GMT -3:00) Argentine Time (America/Buenos_Aires)' },
  { value: 'America/Catamarca', label: '(GMT -3:00) Argentine Time (America/Catamarca)' },
  { value: 'America/Cayenne', label: '(GMT -3:00) French Guiana Time (America/Cayenne)' },
  { value: 'America/Cordoba', label: '(GMT -3:00) Argentine Time (America/Cordoba)' },
  { value: 'America/Fortaleza', label: '(GMT -3:00) Brasilia Time (America/Fortaleza)' },
  { value: 'America/Godthab', label: '(GMT -3:00) Western Greenland Summer Time (America/Godthab)' },
  { value: 'America/Jujuy', label: '(GMT -3:00) Argentine Time (America/Jujuy)' },
  { value: 'America/Maceio', label: '(GMT -3:00) Brasilia Time (America/Maceio)' },
  { value: 'America/Mendoza', label: '(GMT -3:00) Argentine Time (America/Mendoza)' },
  { value: 'America/Miquelon', label: '(GMT -3:00) Pierre & Miquelon Daylight Time (America/Miquelon)' },
  { value: 'America/Montevideo', label: '(GMT -3:00) Uruguay Time (America/Montevideo)' },
  { value: 'America/Paramaribo', label: '(GMT -3:00) Suriname Time (America/Paramaribo)' },
  { value: 'America/Recife', label: '(GMT -3:00) Brasilia Time (America/Recife)' },
  { value: 'America/Rosario', label: '(GMT -3:00) Argentine Time (America/Rosario)' },
  { value: 'America/Sao_Paulo', label: '(GMT -3:00) Brasilia Time (America/Sao_Paulo)' },
  { value: 'Antarctica/Rothera', label: '(GMT -3:00) Rothera Time (Antarctica/Rothera)' },
  { value: 'BET', label: '(GMT -3:00) Brasilia Time (BET)' },
  { value: 'Brazil/East', label: '(GMT -3:00) Brasilia Time (Brazil/East)' },
  { value: 'Etc/GMT+3', label: '(GMT -3:00) GMT-03:00 (Etc/GMT+3)' },
  { value: 'America/Noronha', label: '(GMT -2:00) Fernando de Noronha Time (America/Noronha)' },
  { value: 'Atlantic/South_Georgia', label: '(GMT -2:00) South Georgia Standard Time (Atlantic/South_Georgia)' },
  { value: 'Brazil/DeNoronha', label: '(GMT -2:00) Fernando de Noronha Time (Brazil/DeNoronha)' },
  { value: 'Etc/GMT+2', label: '(GMT -2:00) GMT-02:00 (Etc/GMT+2)' },
  { value: 'America/Scoresbysund', label: '(GMT -1:00) Eastern Greenland Summer Time (America/Scoresbysund)' },
  { value: 'Atlantic/Azores', label: '(GMT -1:00) Azores Summer Time (Atlantic/Azores)' },
  { value: 'Atlantic/Cape_Verde', label: '(GMT -1:00) Cape Verde Time (Atlantic/Cape_Verde)' },
  { value: 'Etc/GMT+1', label: '(GMT -1:00) GMT-01:00 (Etc/GMT+1)' },
  { value: 'Africa/Abidjan', label: '(GMT 0:00) Greenwich Mean Time (Africa/Abidjan)' },
  { value: 'Africa/Accra', label: '(GMT 0:00) Greenwich Mean Time (Africa/Accra)' },
  { value: 'Africa/Bamako', label: '(GMT 0:00) Greenwich Mean Time (Africa/Bamako)' },
  { value: 'Africa/Banjul', label: '(GMT 0:00) Greenwich Mean Time (Africa/Banjul)' },
  { value: 'Africa/Bissau', label: '(GMT 0:00) Greenwich Mean Time (Africa/Bissau)' },
  { value: 'Africa/Casablanca', label: '(GMT 0:00) Western European Time (Africa/Casablanca)' },
  { value: 'Africa/Conakry', label: '(GMT 0:00) Greenwich Mean Time (Africa/Conakry)' },
  { value: 'Africa/Dakar', label: '(GMT 0:00) Greenwich Mean Time (Africa/Dakar)' },
  { value: 'Africa/El_Aaiun', label: '(GMT 0:00) Western European Time (Africa/El_Aaiun)' },
  { value: 'Africa/Freetown', label: '(GMT 0:00) Greenwich Mean Time (Africa/Freetown)' },
  { value: 'Africa/Lome', label: '(GMT 0:00) Greenwich Mean Time (Africa/Lome)' },
  { value: 'Africa/Monrovia', label: '(GMT 0:00) Greenwich Mean Time (Africa/Monrovia)' },
  { value: 'Africa/Nouakchott', label: '(GMT 0:00) Greenwich Mean Time (Africa/Nouakchott)' },
  { value: 'Africa/Ouagadougou', label: '(GMT 0:00) Greenwich Mean Time (Africa/Ouagadougou)' },
  { value: 'Africa/Sao_Tome', label: '(GMT 0:00) Greenwich Mean Time (Africa/Sao_Tome)' },
  { value: 'Africa/Timbuktu', label: '(GMT 0:00) Greenwich Mean Time (Africa/Timbuktu)' },
  { value: 'America/Danmarkshavn', label: '(GMT 0:00) Greenwich Mean Time (America/Danmarkshavn)' },
  { value: 'Atlantic/Canary', label: '(GMT 0:00) Western European Summer Time (Atlantic/Canary)' },
  { value: 'Atlantic/Faeroe', label: '(GMT 0:00) Western European Summer Time (Atlantic/Faeroe)' },
  { value: 'Atlantic/Madeira', label: '(GMT 0:00) Western European Summer Time (Atlantic/Madeira)' },
  { value: 'Atlantic/Reykjavik', label: '(GMT 0:00) Greenwich Mean Time (Atlantic/Reykjavik)' },
  { value: 'Atlantic/St_Helena', label: '(GMT 0:00) Greenwich Mean Time (Atlantic/St_Helena)' },
  { value: 'Eire', label: '(GMT 0:00) Irish Summer Time (Eire)' },
  { value: 'Etc/GMT', label: '(GMT 0:00) GMT+00:00 (Etc/GMT)' },
  { value: 'Etc/GMT+0', label: '(GMT 0:00) GMT+00:00 (Etc/GMT+0)' },
  { value: 'Etc/GMT-0', label: '(GMT 0:00) GMT+00:00 (Etc/GMT-0)' },
  { value: 'Etc/GMT0', label: '(GMT 0:00) GMT+00:00 (Etc/GMT0)' },
  { value: 'Etc/Greenwich', label: '(GMT 0:00) Greenwich Mean Time (Etc/Greenwich)' },
  { value: 'Etc/UCT', label: '(GMT 0:00) Coordinated Universal Time (Etc/UCT)' },
  { value: 'Etc/UTC', label: '(GMT 0:00) Coordinated Universal Time (Etc/UTC)' },
  { value: 'Etc/Universal', label: '(GMT 0:00) Coordinated Universal Time (Etc/Universal)' },
  { value: 'Etc/Zulu', label: '(GMT 0:00) Coordinated Universal Time (Etc/Zulu)' },
  { value: 'Europe/Belfast', label: '(GMT 0:00) British Summer Time (Europe/Belfast)' },
  { value: 'Europe/Dublin', label: '(GMT 0:00) Irish Summer Time (Europe/Dublin)' },
  { value: 'Europe/Guernsey', label: '(GMT 0:00) British Summer Time (Europe/Guernsey)' },
  { value: 'Europe/Isle_of_Man', label: '(GMT 0:00) British Summer Time (Europe/Isle_of_Man)' },
  { value: 'Europe/Jersey', label: '(GMT 0:00) British Summer Time (Europe/Jersey)' },
  { value: 'Europe/Lisbon', label: '(GMT 0:00) Western European Summer Time (Europe/Lisbon)' },
  { value: 'Europe/London', label: '(GMT 0:00) British Summer Time (Europe/London)' },
  { value: 'GB', label: '(GMT 0:00) British Summer Time (GB)' },
  { value: 'GB-Eire', label: '(GMT 0:00) British Summer Time (GB-Eire)' },
  { value: 'GMT', label: '(GMT 0:00) Greenwich Mean Time (GMT)' },
  { value: 'GMT0', label: '(GMT 0:00) GMT+00:00 (GMT0)' },
  { value: 'Greenwich', label: '(GMT 0:00) Greenwich Mean Time (Greenwich)' },
  { value: 'Iceland', label: '(GMT 0:00) Greenwich Mean Time (Iceland)' },
  { value: 'Portugal', label: '(GMT 0:00) Western European Summer Time (Portugal)' },
  { value: 'UCT', label: '(GMT 0:00) Coordinated Universal Time (UCT)' },
  { value: 'UTC', label: '(GMT 0:00) Coordinated Universal Time (UTC)' },
  { value: 'Universal', label: '(GMT 0:00) Coordinated Universal Time (Universal)' },
  { value: 'WET', label: '(GMT 0:00) Western European Summer Time (WET)' },
  { value: 'Zulu', label: '(GMT 0:00) Coordinated Universal Time (Zulu)' },
  { value: 'Africa/Algiers', label: '(GMT 1:00) Central European Time (Africa/Algiers)' },
  { value: 'Africa/Bangui', label: '(GMT 1:00) Western African Time (Africa/Bangui)' },
  { value: 'Africa/Brazzaville', label: '(GMT 1:00) Western African Time (Africa/Brazzaville)' },
  { value: 'Africa/Ceuta', label: '(GMT 1:00) Central European Summer Time (Africa/Ceuta)' },
  { value: 'Africa/Douala', label: '(GMT 1:00) Western African Time (Africa/Douala)' },
  { value: 'Africa/Kinshasa', label: '(GMT 1:00) Western African Time (Africa/Kinshasa)' },
  { value: 'Africa/Lagos', label: '(GMT 1:00) Western African Time (Africa/Lagos)' },
  { value: 'Africa/Libreville', label: '(GMT 1:00) Western African Time (Africa/Libreville)' },
  { value: 'Africa/Luanda', label: '(GMT 1:00) Western African Time (Africa/Luanda)' },
  { value: 'Africa/Malabo', label: '(GMT 1:00) Western African Time (Africa/Malabo)' },
  { value: 'Africa/Ndjamena', label: '(GMT 1:00) Western African Time (Africa/Ndjamena)' },
  { value: 'Africa/Niamey', label: '(GMT 1:00) Western African Time (Africa/Niamey)' },
  { value: 'Africa/Porto-Novo', label: '(GMT 1:00) Western African Time (Africa/Porto-Novo)' },
  { value: 'Africa/Tunis', label: '(GMT 1:00) Central European Summer Time (Africa/Tunis)' },
  { value: 'Africa/Windhoek', label: '(GMT 1:00) Western African Summer Time (Africa/Windhoek)' },
  { value: 'Arctic/Longyearbyen', label: '(GMT 1:00) Central European Summer Time (Arctic/Longyearbyen)' },
  { value: 'Atlantic/Jan_Mayen', label: '(GMT 1:00) Central European Summer Time (Atlantic/Jan_Mayen)' },
  { value: 'CET', label: '(GMT 1:00) Central European Summer Time (CET)' },
  { value: 'ECT', label: '(GMT 1:00) Central European Summer Time (ECT)' },
  { value: 'Etc/GMT-1', label: '(GMT 1:00) GMT+01:00 (Etc/GMT-1)' },
  { value: 'Europe/Amsterdam', label: '(GMT 1:00) Central European Summer Time (Europe/Amsterdam)' },
  { value: 'Europe/Andorra', label: '(GMT 1:00) Central European Summer Time (Europe/Andorra)' },
  { value: 'Europe/Belgrade', label: '(GMT 1:00) Central European Summer Time (Europe/Belgrade)' },
  { value: 'Europe/Berlin', label: '(GMT 1:00) Central European Summer Time (Europe/Berlin)' },
  { value: 'Europe/Bratislava', label: '(GMT 1:00) Central European Summer Time (Europe/Bratislava)' },
  { value: 'Europe/Brussels', label: '(GMT 1:00) Central European Summer Time (Europe/Brussels)' },
  { value: 'Europe/Budapest', label: '(GMT 1:00) Central European Summer Time (Europe/Budapest)' },
  { value: 'Europe/Copenhagen', label: '(GMT 1:00) Central European Summer Time (Europe/Copenhagen)' },
  { value: 'Europe/Gibraltar', label: '(GMT 1:00) Central European Summer Time (Europe/Gibraltar)' },
  { value: 'Europe/Ljubljana', label: '(GMT 1:00) Central European Summer Time (Europe/Ljubljana)' },
  { value: 'Europe/Luxembourg', label: '(GMT 1:00) Central European Summer Time (Europe/Luxembourg)' },
  { value: 'Europe/Madrid', label: '(GMT 1:00) Central European Summer Time (Europe/Madrid)' },
  { value: 'Europe/Malta', label: '(GMT 1:00) Central European Summer Time (Europe/Malta)' },
  { value: 'Europe/Monaco', label: '(GMT 1:00) Central European Summer Time (Europe/Monaco)' },
  { value: 'Europe/Oslo', label: '(GMT 1:00) Central European Summer Time (Europe/Oslo)' },
  { value: 'Europe/Paris', label: '(GMT 1:00) Central European Summer Time (Europe/Paris)' },
  { value: 'Europe/Podgorica', label: '(GMT 1:00) Central European Summer Time (Europe/Podgorica)' },
  { value: 'Europe/Prague', label: '(GMT 1:00) Central European Summer Time (Europe/Prague)' },
  { value: 'Europe/Rome', label: '(GMT 1:00) Central European Summer Time (Europe/Rome)' },
  { value: 'Europe/San_Marino', label: '(GMT 1:00) Central European Summer Time (Europe/San_Marino)' },
  { value: 'Europe/Sarajevo', label: '(GMT 1:00) Central European Summer Time (Europe/Sarajevo)' },
  { value: 'Europe/Skopje', label: '(GMT 1:00) Central European Summer Time (Europe/Skopje)' },
  { value: 'Europe/Stockholm', label: '(GMT 1:00) Central European Summer Time (Europe/Stockholm)' },
  { value: 'Europe/Tirane', label: '(GMT 1:00) Central European Summer Time (Europe/Tirane)' },
  { value: 'Europe/Vaduz', label: '(GMT 1:00) Central European Summer Time (Europe/Vaduz)' },
  { value: 'Europe/Vatican', label: '(GMT 1:00) Central European Summer Time (Europe/Vatican)' },
  { value: 'Europe/Vienna', label: '(GMT 1:00) Central European Summer Time (Europe/Vienna)' },
  { value: 'Europe/Warsaw', label: '(GMT 1:00) Central European Summer Time (Europe/Warsaw)' },
  { value: 'Europe/Zagreb', label: '(GMT 1:00) Central European Summer Time (Europe/Zagreb)' },
  { value: 'Europe/Zurich', label: '(GMT 1:00) Central European Summer Time (Europe/Zurich)' },
  { value: 'MET', label: '(GMT 1:00) Middle Europe Summer Time (MET)' },
  { value: 'Poland', label: '(GMT 1:00) Central European Summer Time (Poland)' },
  { value: 'ART', label: '(GMT 2:00) Eastern European Summer Time (ART)' },
  { value: 'Africa/Blantyre', label: '(GMT 2:00) Central African Time (Africa/Blantyre)' },
  { value: 'Africa/Bujumbura', label: '(GMT 2:00) Central African Time (Africa/Bujumbura)' },
  { value: 'Africa/Cairo', label: '(GMT 2:00) Eastern European Summer Time (Africa/Cairo)' },
  { value: 'Africa/Gaborone', label: '(GMT 2:00) Central African Time (Africa/Gaborone)' },
  { value: 'Africa/Harare', label: '(GMT 2:00) Central African Time (Africa/Harare)' },
  { value: 'Africa/Johannesburg', label: '(GMT 2:00) South Africa Standard Time (Africa/Johannesburg)' },
  { value: 'Africa/Kigali', label: '(GMT 2:00) Central African Time (Africa/Kigali)' },
  { value: 'Africa/Lubumbashi', label: '(GMT 2:00) Central African Time (Africa/Lubumbashi)' },
  { value: 'Africa/Lusaka', label: '(GMT 2:00) Central African Time (Africa/Lusaka)' },
  { value: 'Africa/Maputo', label: '(GMT 2:00) Central African Time (Africa/Maputo)' },
  { value: 'Africa/Maseru', label: '(GMT 2:00) South Africa Standard Time (Africa/Maseru)' },
  { value: 'Africa/Mbabane', label: '(GMT 2:00) South Africa Standard Time (Africa/Mbabane)' },
  { value: 'Africa/Tripoli', label: '(GMT 2:00) Eastern European Time (Africa/Tripoli)' },
  { value: 'Asia/Amman', label: '(GMT 2:00) Eastern European Summer Time (Asia/Amman)' },
  { value: 'Asia/Beirut', label: '(GMT 2:00) Eastern European Summer Time (Asia/Beirut)' },
  { value: 'Asia/Damascus', label: '(GMT 2:00) Eastern European Summer Time (Asia/Damascus)' },
  { value: 'Asia/Gaza', label: '(GMT 2:00) Eastern European Summer Time (Asia/Gaza)' },
  { value: 'Asia/Istanbul', label: '(GMT 2:00) Eastern European Summer Time (Asia/Istanbul)' },
  { value: 'Asia/Jerusalem', label: '(GMT 2:00) Israel Standard Time (Asia/Jerusalem)' },
  { value: 'Asia/Nicosia', label: '(GMT 2:00) Eastern European Summer Time (Asia/Nicosia)' },
  { value: 'Asia/Tel_Aviv', label: '(GMT 2:00) Israel Standard Time (Asia/Tel_Aviv)' },
  { value: 'CAT', label: '(GMT 2:00) Central African Time (CAT)' },
  { value: 'EET', label: '(GMT 2:00) Eastern European Summer Time (EET)' },
  { value: 'Egypt', label: '(GMT 2:00) Eastern European Summer Time (Egypt)' },
  { value: 'Etc/GMT-2', label: '(GMT 2:00) GMT+02:00 (Etc/GMT-2)' },
  { value: 'Europe/Athens', label: '(GMT 2:00) Eastern European Summer Time (Europe/Athens)' },
  { value: 'Europe/Bucharest', label: '(GMT 2:00) Eastern European Summer Time (Europe/Bucharest)' },
  { value: 'Europe/Chisinau', label: '(GMT 2:00) Eastern European Summer Time (Europe/Chisinau)' },
  { value: 'Europe/Helsinki', label: '(GMT 2:00) Eastern European Summer Time (Europe/Helsinki)' },
  { value: 'Europe/Istanbul', label: '(GMT 2:00) Eastern European Summer Time (Europe/Istanbul)' },
  { value: 'Europe/Kaliningrad', label: '(GMT 2:00) Eastern European Summer Time (Europe/Kaliningrad)' },
  { value: 'Europe/Kiev', label: '(GMT 2:00) Eastern European Summer Time (Europe/Kiev)' },
  { value: 'Europe/Mariehamn', label: '(GMT 2:00) Eastern European Summer Time (Europe/Mariehamn)' },
  { value: 'Europe/Minsk', label: '(GMT 2:00) Eastern European Summer Time (Europe/Minsk)' },
  { value: 'Europe/Nicosia', label: '(GMT 2:00) Eastern European Summer Time (Europe/Nicosia)' },
  { value: 'Europe/Riga', label: '(GMT 2:00) Eastern European Summer Time (Europe/Riga)' },
  { value: 'Europe/Simferopol', label: '(GMT 2:00) Eastern European Summer Time (Europe/Simferopol)' },
  { value: 'Europe/Sofia', label: '(GMT 2:00) Eastern European Summer Time (Europe/Sofia)' },
  { value: 'Europe/Tallinn', label: '(GMT 2:00) Eastern European Summer Time (Europe/Tallinn)' },
  { value: 'Europe/Tiraspol', label: '(GMT 2:00) Eastern European Summer Time (Europe/Tiraspol)' },
  { value: 'Europe/Uzhgorod', label: '(GMT 2:00) Eastern European Summer Time (Europe/Uzhgorod)' },
  { value: 'Europe/Vilnius', label: '(GMT 2:00) Eastern European Summer Time (Europe/Vilnius)' },
  { value: 'Europe/Zaporozhye', label: '(GMT 2:00) Eastern European Summer Time (Europe/Zaporozhye)' },
  { value: 'Israel', label: '(GMT 2:00) Israel Standard Time (Israel)' },
  { value: 'Libya', label: '(GMT 2:00) Eastern European Time (Libya)' },
  { value: 'Türkiye', label: '(GMT 2:00) Eastern European Summer Time (Türkiye)' },
  { value: 'Africa/Addis_Ababa', label: '(GMT 3:00) Eastern African Time (Africa/Addis_Ababa)' },
  { value: 'Africa/Asmera', label: '(GMT 3:00) Eastern African Time (Africa/Asmera)' },
  { value: 'Africa/Dar_es_Salaam', label: '(GMT 3:00) Eastern African Time (Africa/Dar_es_Salaam)' },
  { value: 'Africa/Djibouti', label: '(GMT 3:00) Eastern African Time (Africa/Djibouti)' },
  { value: 'Africa/Kampala', label: '(GMT 3:00) Eastern African Time (Africa/Kampala)' },
  { value: 'Africa/Khartoum', label: '(GMT 2:00) Central African Time (Africa/Khartoum)' },
  { value: 'Africa/Mogadishu', label: '(GMT 3:00) Eastern African Time (Africa/Mogadishu)' },
  { value: 'Africa/Nairobi', label: '(GMT 3:00) Eastern African Time (Africa/Nairobi)' },
  { value: 'Antarctica/Syowa', label: '(GMT 3:00) Syowa Time (Antarctica/Syowa)' },
  { value: 'Asia/Aden', label: '(GMT 3:00) Arabia Standard Time (Asia/Aden)' },
  { value: 'Asia/Baghdad', label: '(GMT 3:00) Arabia Daylight Time (Asia/Baghdad)' },
  { value: 'Asia/Bahrain', label: '(GMT 3:00) Arabia Standard Time (Asia/Bahrain)' },
  { value: 'Asia/Kuwait', label: '(GMT 3:00) Arabia Standard Time (Asia/Kuwait)' },
  { value: 'Asia/Qatar', label: '(GMT 3:00) Arabia Standard Time (Asia/Qatar)' },
  { value: 'Asia/Riyadh', label: '(GMT 3:00) Arabia Standard Time (Asia/Riyadh)' },
  { value: 'EAT', label: '(GMT 3:00) Eastern African Time (EAT)' },
  { value: 'Etc/GMT-3', label: '(GMT 3:00) GMT+03:00 (Etc/GMT-3)' },
  { value: 'Europe/Moscow', label: '(GMT 3:00) Moscow Daylight Time (Europe/Moscow)' },
  { value: 'Europe/Volgograd', label: '(GMT 3:00) Volgograd Summer Time (Europe/Volgograd)' },
  { value: 'Indian/Antananarivo', label: '(GMT 3:00) Eastern African Time (Indian/Antananarivo)' },
  { value: 'Indian/Comoro', label: '(GMT 3:00) Eastern African Time (Indian/Comoro)' },
  { value: 'Indian/Mayotte', label: '(GMT 3:00) Eastern African Time (Indian/Mayotte)' },
  { value: 'W-SU', label: '(GMT 3:00) Moscow Daylight Time (W-SU)' },
  { value: 'Asia/Riyadh87', label: '(GMT 3:7 ) GMT+03:07(Asia/Riyadh87)' },
  { value: 'Asia/Riyadh88', label: '(GMT 3:7 ) GMT+03:07(Asia/Riyadh88)' },
  { value: 'Asia/Riyadh89', label: '(GMT 3:7 ) GMT+03:07(Asia/Riyadh89)' },
  { value: 'Mideast/Riyadh87', label: '(GMT 3:7 ) GMT+03:07(Mideast/Riyadh87)' },
  { value: 'Mideast/Riyadh88', label: '(GMT 3:7 ) GMT+03:07(Mideast/Riyadh88)' },
  { value: 'Mideast/Riyadh89', label: '(GMT 3:7 ) GMT+03:07(Mideast/Riyadh89)' },
  { value: 'Asia/Tehran', label: '(GMT 3:30) Iran Standard Time (Asia/Tehran)' },
  { value: 'Iran', label: '(GMT 3:30) Iran Standard Time (Iran)' },
  { value: 'Asia/Baku', label: '(GMT 4:00) Azerbaijan Summer Time (Asia/Baku)' },
  { value: 'Asia/Dubai', label: '(GMT 4:00) Gulf Standard Time (Asia/Dubai)' },
  { value: 'Asia/Muscat', label: '(GMT 4:00) Gulf Standard Time (Asia/Muscat)' },
  { value: 'Asia/Tbilisi', label: '(GMT 4:00) Georgia Time (Asia/Tbilisi)' },
  { value: 'Asia/Yerevan', label: '(GMT 4:00) Armenia Summer Time (Asia/Yerevan)' },
  { value: 'Etc/GMT-4', label: '(GMT 4:00) GMT+04:00 (Etc/GMT-4)' },
  { value: 'Europe/Samara', label: '(GMT 4:00) Samara Summer Time (Europe/Samara)' },
  { value: 'Indian/Mahe', label: '(GMT 4:00) Seychelles Time (Indian/Mahe)' },
  { value: 'Indian/Mauritius', label: '(GMT 4:00) Mauritius Time (Indian/Mauritius)' },
  { value: 'Indian/Reunion', label: '(GMT 4:00) Reunion Time (Indian/Reunion)' },
  { value: 'NET', label: '(GMT 4:00) Armenia Summer Time (NET)' },
  { value: 'Asia/Kabul', label: '(GMT 4:30) Afghanistan Time (Asia/Kabul)' },
  { value: 'Asia/Aqtau', label: '(GMT 5:00) Aqtau Time (Asia/Aqtau)' },
  { value: 'Asia/Aqtobe', label: '(GMT 5:00) Aqtobe Time (Asia/Aqtobe)' },
  { value: 'Asia/Ashgabat', label: '(GMT 5:00) Turkmenistan Time (Asia/Ashgabat)' },
  { value: 'Asia/Ashkhabad', label: '(GMT 5:00) Turkmenistan Time (Asia/Ashkhabad)' },
  { value: 'Asia/Dushanbe', label: '(GMT 5:00) Tajikistan Time (Asia/Dushanbe)' },
  { value: 'Asia/Karachi', label: '(GMT 5:00) Pakistan Time (Asia/Karachi)' },
  { value: 'Asia/Oral', label: '(GMT 5:00) Oral Time (Asia/Oral)' },
  { value: 'Asia/Samarkand', label: '(GMT 5:00) Uzbekistan Time (Asia/Samarkand)' },
  { value: 'Asia/Tashkent', label: '(GMT 5:00) Uzbekistan Time (Asia/Tashkent)' },
  { value: 'Asia/Yekaterinburg', label: '(GMT 5:00) Yekaterinburg Summer Time (Asia/Yekaterinburg)' },
  { value: 'Etc/GMT-5', label: '(GMT 5:00) GMT+05:00 (Etc/GMT-5)' },
  { value: 'Indian/Kerguelen', label: '(GMT 5:00) French Southern & Antarctic Lands Time (Indian/Kerguelen)' },
  { value: 'Indian/Maldives', label: '(GMT 5:00) Maldives Time (Indian/Maldives)' },
  { value: 'PLT', label: '(GMT 5:00) Pakistan Time (PLT)' },
  { value: 'Asia/Calcutta', label: '(GMT 5:30) India Standard Time (Asia/Calcutta)' },
  { value: 'Asia/Colombo', label: '(GMT 5:30) Sri Lanka Time (Asia/Colombo)' },
  { value: 'Asia/Kolkata', label: '(GMT 5:30) India Standard Time (Asia/Kolkata)' },
  { value: 'IST', label: '(GMT 5:30) India Standard Time (IST)' },
  { value: 'Asia/Katmandu', label: '(GMT 5:45 ) Nepal Time (Asia/Katmandu)' },
  { value: 'Antarctica/Mawson', label: '(GMT 6:00) Mawson Time (Antarctica/Mawson)' },
  { value: 'Antarctica/Vostok', label: '(GMT 6:00) Vostok Time (Antarctica/Vostok)' },
  { value: 'Asia/Almaty', label: '(GMT 6:00) Alma-Ata Time (Asia/Almaty)' },
  { value: 'Asia/Bishkek', label: '(GMT 6:00) Kirgizstan Time (Asia/Bishkek)' },
  { value: 'Asia/Dacca', label: '(GMT 6:00) Bangladesh Time (Asia/Dacca)' },
  { value: 'Asia/Dhaka', label: '(GMT 6:00) Bangladesh Time (Asia/Dhaka)' },
  { value: 'Asia/Novosibirsk', label: '(GMT 6:00) Novosibirsk Summer Time (Asia/Novosibirsk)' },
  { value: 'Asia/Omsk', label: '(GMT 6:00) Omsk Summer Time (Asia/Omsk)' },
  { value: 'Asia/Qyzylorda', label: '(GMT 6:00) Qyzylorda Time (Asia/Qyzylorda)' },
  { value: 'Asia/Thimbu', label: '(GMT 6:00) Bhutan Time (Asia/Thimbu)' },
  { value: 'Asia/Thimphu', label: '(GMT 6:00) Bhutan Time (Asia/Thimphu)' },
  { value: 'BST', label: '(GMT 6:00) Bangladesh Time (BST)' },
  { value: 'Etc/GMT-6', label: '(GMT 6:00) GMT+06:00 (Etc/GMT-6)' },
  { value: 'Indian/Chagos', label: '(GMT 6:00) Indian Ocean Territory Time (Indian/Chagos)' },
  { value: 'Asia/Rangoon', label: '(GMT 6:30) Myanmar Time (Asia/Rangoon)' },
  { value: 'Indian/Cocos', label: '(GMT 6:30) Cocos Islands Time (Indian/Cocos)' },
  { value: 'Antarctica/Davis', label: '(GMT 7:00) Davis Time (Antarctica/Davis)' },
  { value: 'Asia/Bangkok', label: '(GMT 7:00) Indochina Time (Asia/Bangkok)' },
  { value: 'Asia/Ho_Chi_Minh', label: '(GMT 7:00) Indochina Time (Asia/Ho_Chi_Minh)' },
  { value: 'Asia/Hovd', label: '(GMT 7:00) Hovd Summer Time (Asia/Hovd)' },
  { value: 'Asia/Jakarta', label: '(GMT 7:00) West Indonesia Time (Asia/Jakarta)' },
  { value: 'Asia/Krasnoyarsk', label: '(GMT 7:00) Krasnoyarsk Summer Time (Asia/Krasnoyarsk)' },
  { value: 'Asia/Phnom_Penh', label: '(GMT 7:00) Indochina Time (Asia/Phnom_Penh)' },
  { value: 'Asia/Pontianak', label: '(GMT 7:00) West Indonesia Time (Asia/Pontianak)' },
  { value: 'Asia/Saigon', label: '(GMT 7:00) Indochina Time (Asia/Saigon)' },
  { value: 'Asia/Vientiane', label: '(GMT 7:00) Indochina Time (Asia/Vientiane)' },
  { value: 'Etc/GMT-7', label: '(GMT 7:00) GMT+07:00 (Etc/GMT-7)' },
  { value: 'Indian/Christmas', label: '(GMT 7:00) Christmas Island Time (Indian/Christmas)' },
  { value: 'VST', label: '(GMT 7:00) Indochina Time (VST)' },
  { value: 'Antarctica/Casey', label: '(GMT 8:00) Western Standard Time (Australia)(Antarctica/Casey)' },
  { value: 'Asia/Brunei', label: '(GMT 8:00) Brunei Time (Asia/Brunei)' },
  { value: 'Asia/Chongqing', label: '(GMT 8:00) China Standard Time (Asia/Chongqing)' },
  { value: 'Asia/Harbin', label: '(GMT 8:00) China Standard Time (Asia/Harbin)' },
  { value: 'Asia/Hong_Kong', label: '(GMT 8:00) Hong Kong Time (Asia/Hong_Kong)' },
  { value: 'Asia/Irkutsk', label: '(GMT 8:00) Irkutsk Summer Time (Asia/Irkutsk)' },
  { value: 'Asia/Kashgar', label: '(GMT 8:00) China Standard Time (Asia/Kashgar)' },
  { value: 'Asia/Kuala_Lumpur', label: '(GMT 8:00) Malaysia Time (Asia/Kuala_Lumpur)' },
  { value: 'Asia/Kuching', label: '(GMT 8:00) Malaysia Time (Asia/Kuching)' },
  { value: 'Asia/Macao', label: '(GMT 8:00) China Standard Time (Asia/Macao)' },
  { value: 'Asia/Makassar', label: '(GMT 8:00) Central Indonesia Time (Asia/Makassar)' },
  { value: 'Asia/Manila', label: '(GMT 8:00) Philippines Time (Asia/Manila)' },
  { value: 'Asia/Shanghai', label: '(GMT 8:00) China Standard Time (Asia/Shanghai)' },
  { value: 'Asia/Singapore', label: '(GMT 8:00) Singapore Time (Asia/Singapore)' },
  { value: 'Asia/Taipei', label: '(GMT 8:00) China Standard Time (Asia/Taipei)' },
  { value: 'Asia/Ujung_Pandang', label: '(GMT 8:00) Central Indonesia Time (Asia/Ujung_Pandang)' },
  { value: 'Asia/Ulaanbaatar', label: '(GMT 8:00) Ulaanbaatar Summer Time (Asia/Ulaanbaatar)' },
  { value: 'Asia/Ulan_Bator', label: '(GMT 8:00) Ulaanbaatar Summer Time (Asia/Ulan_Bator)' },
  { value: 'Asia/Urumqi', label: '(GMT 8:00) China Standard Time (Asia/Urumqi)' },
  { value: 'Australia/Perth', label: '(GMT 8:00) Western Standard Time (Australia)(Australia/Perth)' },
  { value: 'Australia/West', label: '(GMT 8:00) Western Standard Time (Australia)(Australia/West)' },
  { value: 'CTT', label: '(GMT 8:00) China Standard Time (CTT)' },
  { value: 'Etc/GMT-8', label: '(GMT 8:00) GMT+08:00 (Etc/GMT-8)' },
  { value: 'PRC', label: '(GMT 8:00) China Standard Time (PRC)' },
  { value: 'Singapore', label: '(GMT 8:00) Singapore Time (Singapore)' },
  { value: 'Asia/Choibalsan', label: '(GMT 9:00) Choibalsan Summer Time (Asia/Choibalsan)' },
  { value: 'Asia/Dili', label: '(GMT 9:00) East Timor Time (Asia/Dili)' },
  { value: 'Asia/Jayapura', label: '(GMT 9:00) East Indonesia Time (Asia/Jayapura)' },
  { value: 'Asia/Pyongyang', label: '(GMT 9:00) Korea Standard Time (Asia/Pyongyang)' },
  { value: 'Asia/Seoul', label: '(GMT 9:00) Korea Standard Time (Asia/Seoul)' },
  { value: 'Asia/Tokyo', label: '(GMT 9:00) Japan Standard Time (Asia/Tokyo)' },
  { value: 'Asia/Yakutsk', label: '(GMT 9:00) Yaktsk Summer Time (Asia/Yakutsk)' },
  { value: 'Etc/GMT-9', label: '(GMT 9:00) GMT+09:00 (Etc/GMT-9)' },
  { value: 'JST', label: '(GMT 9:00) Japan Standard Time (JST)' },
  { value: 'Japan', label: '(GMT 9:00) Japan Standard Time (Japan)' },
  { value: 'Pacific/Palau', label: '(GMT 9:00) Palau Time (Pacific/Palau)' },
  { value: 'ROK', label: '(GMT 9:00) Korea Standard Time (ROK)' },
  { value: 'ACT', label: '(GMT 9:30) Central Standard Time (Northern Territory)(ACT)' },
  { value: 'Australia/Adelaide', label: '(GMT 9:30) Central Standard Time (South Australia)(Australia/Adelaide)' },
  { value: 'Australia/Broken_Hill', label: '(GMT 9:30) Central Standard Time (South Australia/New South Wales)(Australia/Broken_Hill)' },
  { value: 'Australia/Darwin', label: '(GMT 9:30) Central Standard Time (Northern Territory)(Australia/Darwin)' },
  { value: 'Australia/North', label: '(GMT 9:30) Central Standard Time (Northern Territory)(Australia/North)' },
  { value: 'Australia/South', label: '(GMT 9:30) Central Standard Time (South Australia)(Australia/South)' },
  { value: 'Australia/Yancowinna', label: '(GMT 9:30) Central Standard Time (South Australia/New South Wales)(Australia/Yancowinna)' },
  { value: 'AET', label: '(GMT 10:00) Eastern Standard Time (New South Wales)(AET)' },
  { value: 'Antarctica/DumontDUrville', label: '(GMT 10:00) Dumont-d Urville Time (Antarctica/DumontDUrville)' },
  { value: 'Asia/Sakhalin', label: '(GMT 10:00) Sakhalin Summer Time (Asia/Sakhalin)' },
  { value: 'Asia/Vladivostok', label: '(GMT 10:00) Vladivostok Summer Time (Asia/Vladivostok)' },
  { value: 'Australia/ACT', label: '(GMT 10:00) Eastern Standard Time (New South Wales)(Australia/ACT)' },
  { value: 'Australia/Brisbane', label: '(GMT 10:00) Eastern Standard Time (Queensland)(Australia/Brisbane)' },
  { value: 'Australia/Canberra', label: '(GMT 10:00) Eastern Standard Time (New South Wales)(Australia/Canberra)' },
  { value: 'Australia/Currie', label: '(GMT 10:00) Eastern Standard Time (New South Wales)(Australia/Currie)' },
  { value: 'Australia/Hobart', label: '(GMT 10:00) Eastern Standard Time (Tasmania)(Australia/Hobart)' },
  { value: 'Australia/Lindeman', label: '(GMT 10:00) Eastern Standard Time (Queensland)(Australia/Lindeman)' },
  { value: 'Australia/Melbourne', label: '(GMT 10:00) Eastern Standard Time (Victoria)(Australia/Melbourne)' },
  { value: 'Australia/NSW', label: '(GMT 10:00) Eastern Standard Time (New South Wales)(Australia/NSW)' },
  { value: 'Australia/Queensland', label: '(GMT 10:00) Eastern Standard Time (Queensland)(Australia/Queensland)' },
  { value: 'Australia/Sydney', label: '(GMT 10:00) Eastern Standard Time (New South Wales)(Australia/Sydney)' },
  { value: 'Australia/Tasmania', label: '(GMT 10:00) Eastern Standard Time (Tasmania)(Australia/Tasmania)' },
  { value: 'Australia/Victoria', label: '(GMT 10:00) Eastern Standard Time (Victoria)(Australia/Victoria)' },
  { value: 'Etc/GMT-10', label: '(GMT 10:00) GMT+10:00 (Etc/GMT-10)(Etc/GMT-10)' },
  { value: 'Pacific/Guam', label: '(GMT 10:00) Chamorro Standard Time (Pacific/Guam)' },
  { value: 'Pacific/Port_Moresby', label: '(GMT 10:00) Papua New Guinea Time (Pacific/Port_Moresby)' },
  { value: 'Pacific/Saipan', label: '(GMT 10:00) Chamorro Standard Time (Pacific/Saipan)' },
  { value: 'Pacific/Truk', label: '(GMT 10:00) Truk Time (Pacific/Truk)' },
  { value: 'Pacific/Yap', label: '(GMT 10:00) Yap Time (Pacific/Yap)' },
  { value: 'Australia/LHI', label: '(GMT 10:30) Load Howe Standard Time (Australia/LHI)' },
  { value: 'Australia/Lord_Howe', label: '(GMT 10:30) Load Howe Standard Time (Australia/Lord_Howe)' },
  { value: 'Asia/Magadan', label: '(GMT 11:00) Magadan Summer Time (Asia/Magadan)' },
  { value: 'Etc/GMT-11', label: '(GMT 11:00) GMT+11:00 (Etc/GMT-11)' },
  { value: 'Pacific/Efate', label: '(GMT 11:00) Vanuatu Time (Pacific/Efate)' },
  { value: 'Pacific/Guadalcanal', label: '(GMT 11:00) Solomon Is. Time (Pacific/Guadalcanal)' },
  { value: 'Pacific/Kosrae', label: '(GMT 11:00) Kosrae Time (Pacific/Kosrae)' },
  { value: 'Pacific/Noumea', label: '(GMT 11:00) New Caledonia Time (Pacific/Noumea)' },
  { value: 'Pacific/Ponape', label: '(GMT 11:00) Ponape Time (Pacific/Ponape)' },
  { value: 'SST', label: '(GMT 11:00) Solomon Is. Time (SST)' },
  { value: 'Pacific/Norfolk', label: '(GMT 11:30) Norfolk Time (Pacific/Norfolk)' },
  { value: 'Antarctica/McMurdo', label: '(GMT 12:00) New Zealand Standard Time (Antarctica/McMurdo)' },
  { value: 'Antarctica/South_Pole', label: '(GMT 12:00) New Zealand Standard Time (Antarctica/South_Pole)' },
  { value: 'Asia/Anadyr', label: '(GMT 12:00) Anadyr Summer Time (Asia/Anadyr)' },
  { value: 'Asia/Kamchatka', label: '(GMT 12:00) Petropavlovsk-Kamchatski Summer Time (Asia/Kamchatka)' },
  { value: 'Etc/GMT-12', label: '(GMT 12:00) GMT+12:00 (Etc/GMT-12)' },
  { value: 'Kwajalein', label: '(GMT 12:00) Marshall Islands Time (Kwajalein)' },
  { value: 'NST', label: '(GMT 12:00) New Zealand Standard Time (NST)' },
  { value: 'NZ', label: '(GMT 12:00) New Zealand Standard Time (NZ)' },
  { value: 'Pacific/Auckland', label: '(GMT 12:00) New Zealand Standard Time (Pacific/Auckland)' },
  { value: 'Pacific/Fiji', label: '(GMT 12:00) Fiji Time (Pacific/Fiji)' },
  { value: 'Pacific/Funafuti', label: '(GMT 12:00) Tuvalu Time (Pacific/Funafuti)' },
  { value: 'Pacific/Kwajalein', label: '(GMT 12:00) Marshall Islands Time (Pacific/Kwajalein)' },
  { value: 'Pacific/Majuro', label: '(GMT 12:00) Marshall Islands Time (Pacific/Majuro)' },
  { value: 'Pacific/Nauru', label: '(GMT 12:00) Nauru Time (Pacific/Nauru)' },
  { value: 'Pacific/Tarawa', label: '(GMT 12:00) Gilbert Is. Time (Pacific/Tarawa)' },
  { value: 'Pacific/Wake', label: '(GMT 12:00) Wake Time (Pacific/Wake)' },
  { value: 'Pacific/Wallis', label: '(GMT 12:00) Wallis & Futuna Time (Pacific/Wallis)' },
  { value: 'NZ-CHAT', label: '(GMT 12:45 ) Chatham Standard Time (NZ-CHAT)' },
  { value: 'Pacific/Chatham', label: '(GMT 12:45 ) Chatham Standard Time (Pacific/Chatham)' },
  { value: 'Etc/GMT-13', label: '(GMT 13:00) GMT+13:00 (Etc/GMT-13)' },
  { value: 'Pacific/Enderbury', label: '(GMT 13:00) Phoenix Is. Time (Pacific/Enderbury)' },
  { value: 'Pacific/Tongatapu', label: '(GMT 13:00) Tonga Time (Pacific/Tongatapu)' },
  { value: 'Etc/GMT-14', label: '(GMT 14:00) GMT+14:00 (Etc/GMT-14)' },
  { value: 'Pacific/Kiritimati', label: '(GMT 14:00) Line Is. Time (Pacific/Kiritimati)' },
  { value: 'America/Resolute', label: '(GMT -6:00) Central Standard Time (America/Resolute)' },
  { value: '(GMT -7:00) Mountain Standard', label: '(GMT -7:00) Mountain Standard' },
];
