export const TIMEZONES: string[] = [
  "(GMT-12:00) International Date Line West (Etc/GMT+12)",
  "(GMT-11:00) Coordinated Universal Time-11 (Pacific/Pago_Pago)",
  "(GMT-10:00) Hawaii (Pacific/Honolulu)",
  "(GMT-09:00) Alaska (America/Anchorage)",
  "(GMT-08:00) Pacific Time (US & Canada) (America/Los_Angeles)",
  "(GMT-07:00) Mountain Time (US & Canada) (America/Denver)",
  "(GMT-06:00) Central Time (US & Canada) (America/Chicago)",
  "(GMT-05:00) Eastern Time (US & Canada) (America/New_York)",
  "(GMT-04:00) Atlantic Time (Canada) (America/Halifax)",
  "(GMT-03:00) Brasilia (America/Sao_Paulo)",
  "(GMT-02:00) Mid-Atlantic (Atlantic/South_Georgia)",
  "(GMT-01:00) Azores (Atlantic/Azores)",
  "(GMT 0:00) Greenwich Mean Time (Europe/London)",
  "(GMT+01:00) Central European Time (Europe/Berlin)",
  "(GMT+02:00) Eastern European Time (Europe/Helsinki)",
  "(GMT+03:00) Eastern African Time (Africa/Mogadishu)",
  "(GMT+03:00) Arabia Standard Time (Asia/Riyadh)",
  "(GMT+03:30) Iran Standard Time (Asia/Tehran)",
  "(GMT+04:00) Gulf Standard Time (Asia/Dubai)",
  "(GMT+04:30) Afghanistan Time (Asia/Kabul)",
  "(GMT+05:00) Pakistan Standard Time (Asia/Karachi)",
  "(GMT+05:30) India Standard Time (Asia/Kolkata)",
  "(GMT+05:45) Nepal Time (Asia/Kathmandu)",
  "(GMT+06:00) Bangladesh Standard Time (Asia/Dhaka)",
  "(GMT+06:30) Myanmar Time (Asia/Yangon)",
  "(GMT+07:00) Indochina Time (Asia/Bangkok)",
  "(GMT+08:00) China Standard Time (Asia/Shanghai)",
  "(GMT+09:00) Japan Standard Time (Asia/Tokyo)",
  "(GMT+09:30) Australian Central Time (Australia/Adelaide)",
  "(GMT+10:00) Australian Eastern Time (Australia/Sydney)",
  "(GMT+11:00) Solomon Islands Time (Pacific/Guadalcanal)",
  "(GMT+12:00) New Zealand Standard Time (Pacific/Auckland)",
  "(GMT+13:00) Tonga Time (Pacific/Tongatapu)",
  "(GMT+14:00) Line Islands Time (Pacific/Kiritimati)"
];
